### ISSUE TITLE
set kernel type for imported notebooks

### ISSUE THREAD

**Issue by mlovci** [jupyter/jupyterhub#122]
Imported `.ipynb` files are automatically started with a `IPython 3` kernel. Sometimes this should be `IPython 2`. Allow the user to select which type of kernel their `.ipynb` should be run with.

**Comment by mlovci** [comment]
To be clear, I mean __before__ the notebook is open... Not using Toolbar --> Kernel --> Change Kernel

**Comment by minrk** [comment]
JupyterHub is not involved in loading notebooks, that is handled by the single-user IPython server. Notebooks written with IPython 3 store the kernel in their metadata, and will load the appropriate kernel. Notebooks written with IPython 2 or earlier will start with the server's default kernel. This, too, is configurable via `KernelManager.default_kernel_name` if you want to change the default to Python 2 for your own environment.

**Comment by mlovci** [comment]
Thank you, can you tell me how to set this in IPython 3?
