### ISSUE TITLE
Handle failures for `delete_user`

### ISSUE THREAD

**Issue by jhamrick** [jupyter/jupyterhub#123]
If `delete_user` fails because the server doesn't actually exist, then a 404 error is thrown and the front end doesn't handle it nicely (it just doesn't do anything). There should probably be a check for 404's, and then record that the server is gone if that's the case and inform the user, rather than thinking the server is still hanging around somewhere.

**Comment by minrk** [comment]
Looks like this now:

![screen shot 2015-10-08 at 15 01 58](https://cloud.githubusercontent.com/assets/151929/10366881/8ec66924-6dcd-11e5-8593-7c15efe408d0.PNG)
