### ISSUE TITLE
MirrorCode hscrollbar blocks the pointer events

### ISSUE THREAD

**Issue by ckald** [jupyter/jupyterhub#136]
Hello,

Currently there is a bug in a Jupyterhub markup that makes it very annoying to edit long single-line cells. I encounter it in Chrome 39 (OSX). MirrorCode horizontal scrollbar element hangs in front of the cell with `min-height: 18px` and captures all pointer events. To move the cursor around the cell, I have to use a small slit at the very top.

![Proofpic](https://www.dropbox.com/s/ysnw70npgzsjk9e/Screenshot%202015-01-28%2021.47.50.png?dl=1)

Seems that removing the `min-height` attribute should fix the problem

**Comment by minrk** [comment]
Please open IPython issues with the IPython repo. This isn't related to JupyterHub. This may actually be fixed in IPython master.

**Comment by ckald** [comment]
Wow, this was fast. I might be not able to determine where to post issues (and I have a few more). So, I apologize in advance :)

**Comment by minrk** [comment]
JupyterHub spawns single-user servers, and once running, everything is handled by the IPython instance. So if it's not a failure to start, stop, or connect to a notebook server, it's probably not an issue for this repo.
