### ISSUE TITLE
inconsistent db state when spawner fails to start

### ISSUE THREAD

**Issue by minrk** [jupyter/jupyterhub#146]
it's possible for some parts of the Hub to think a server is running when it's not, preventing stop/restart from working.

/cc @jhamrick

**Comment by ssanderson** [comment]
@minrk what does "some parts of the hub" mean here?  There's definitely a window from https://github.com/jupyter/jupyterhub/blob/master/jupyterhub/orm.py#L300 to https://github.com/jupyter/jupyterhub/blob/master/jupyterhub/orm.py#L333 where there's a server entry for the user but the server hasn't actually come up yet.  Is that the issue you're referring to, or is there something else you're seeing?

**Comment by minrk** [comment]
Apparently some APIs are using different information to report whether there's already a server running, so the admin page shows a 'stop' button, but clicking it results in "server isn't running".

This state can happen after a spawner fails to start, not just the spawn pending state, which isn't a problem.

**Comment by minrk** [comment]
The span you are referring to where `server` is defined but not complete is covered by the `User.spawn_pending` state. Where there's inconsistency is in various checks for whether a server is running. #147 adds a `.running` property to be used everywhere, so that at least we don't have the case where the `stop server` button appears, but stopping a user fails with "user's server isn't running". The main issue that cause the problem here is uncaught errors, which would leave server defined after the server failed to start.
