### ISSUE TITLE
Installation on server without internet access is cumbersome

### ISSUE THREAD

**Issue by jdavidheiser** [jupyter/jupyterhub#152]
A common use case for jupyter notebook is going to be corporate servers which live behind a firewall, partitioned off from the greater internet.

For most Python packages, it's possible to use pip to download a bunch of tarballs, then scp those tarballs over to an offline server and install, ie something to the effect of

    pip install  --download='./requirements/' --no-install -r requirements.txt

Similarly, most required software can be downloaded as tarballs or rpm packages.

The Node requirements for jupyter, however, are quite cumbersome to copy over automatically.  It's possible to use the `npmbox` package (https://github.com/arei/npmbox) to wrap up `bower` and `less`, to make those easier to install, but that's not an obvious avenue for most folks.

The entire process is pretty much a beast, and given that npm is notoriously frustrating to use when behind a firewall, I think it'd be worthwhile to do something to make the process of installing the jupyter dependencies less painful.  I'm not sure if this means maintaining a single package of all the needed dependencies, or at least a wiki page detailing the whole process.

I submitted this issue under jupyterhub and not configurable-http-proxy because I think the entire process for being able to install offline could be streamlined, even though the node-related stuff is the biggest pain point currently.

I'd be happy to help out where I can, but I am pretty much muddling my way through figuring this stuff out for myself.

**Comment by minrk** [comment]
I don't think we need to change anything when installing from git. That's always going to require node tools that fetch from the network. But we should be careful to avoid calling less or bower when installing from an sdist, which I doubt we are, since no sdists have been made yet.

If you want to install on a machine with no internet access right now, the best way to do it is to probably build a wheel on a machine that does:

    pip wheel .

and then install with that wheel on the other machine.

**Comment by minrk** [comment]
Just made a first release of 0.1.0, so all you should need is wheels and dependencies.

**Comment by rserbitar** [comment]
This is not working. Jupyterhub still wants to download bower and fails, thus the offline install hangs at:

    Running setup.py install for jupyterhub

**Comment by fossouo** [comment]
Can you please provide a full wheels ?

**Comment by minrk** [comment]
@fossouo JupyterHub has provided wheels for every release. What do you see as missing?

**Comment by fossouo** [comment]
Sorry presently with wheel i build using your github source i got this error : 

/hub/ --hub-api-url=http://localhost:8081/hub/api --ip=localhost
[W 2016-02-07 21:30:40.646 JupyterHub web:1521] 500 POST /hub/login?next= (192.168.56.1): Spawner failed to start [status=0]
[E 2016-02-07 21:30:40.894 JupyterHub log:99]

**Comment by fossouo** [comment]
Is there a proper procedure for it ? Available ?

**Comment by minrk** [comment]
Can you provide more of the logfile? It looks like you cutoff right before the tracaeback showing the error.

**Comment by fossouo** [comment]
yes of course below : 

[I 160208 00:12:02 mediator:62] Spawning jupyterhub-singleuser --user=titi --port=37182 --cookie-name=jupyter-hub-token-titi --base-url=/user/titi --hub-prefix=/hub/ --hub-api-url=http://localhost:8880/hub/api --ip=localhost
[W 2016-02-08 00:12:17.321 JupyterHub web:1521] 500 POST /hub/login?next= (192.168.56.1): Spawner failed to start [status=0]
[E 2016-02-08 00:12:17.773 JupyterHub log:99] {
      "Connection": "close",
      "Accept-Language": "en-US,en;q=0.5",
      "Host": "192.168.56.102",
      "Content-Length": "27",
      "X-Forwarded-For": "192.168.56.1",
      "X-Forwarded-Proto": "http",
      "Accept-Encoding": "gzip, deflate",
      "User-Agent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:43.0) Gecko/20100101 Firefox/43.0",
      "Content-Type": "application/x-www-form-urlencoded",
      "Referer": "http://192.168.56.102/hub/login",
      "X-Forwarded-Port": "80",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"
    }
[E 2016-02-08 00:12:17.773 JupyterHub log:100] 500 POST /hub/login?next= (@192.168.56.1) 30136.90ms
[W 2016-02-08 00:12:34.971 JupyterHub user:218] titi's server never showed up at http://localhost:37182/user/titi after 30 seconds. Giving up
[E 2016-02-08 00:12:35.309 JupyterHub gen:871] Exception in Future <tornado.concurrent.Future object at 0x7f1705a3ad68> after timeout
    Traceback (most recent call last):
      File "/anaconda3/lib/python3.4/site-packages/tornado/gen.py", line 867, in error_callback
        future.result()
      File "/anaconda3/lib/python3.4/site-packages/jupyterhub/user.py", line 234, in spawn
        raise e
      File "/anaconda3/lib/python3.4/site-packages/jupyterhub/user.py", line 210, in spawn
        yield self.server.wait_up(http=True, timeout=spawner.http_timeout)
      File "/anaconda3/lib/python3.4/site-packages/jupyterhub/orm.py", line 110, in wait_up
        yield wait_for_http_server(self.url, timeout=timeout)
      File "/anaconda3/lib/python3.4/site-packages/jupyterhub/utils.py", line 84, in wait_for_http_server
        **locals()
    TimeoutError: Server at http://localhost:37182/user/titi didn't respond in 30 seconds

^C
Interrupted

**Comment by minrk** [comment]
What spawner are you using? What version of JupyterHub (release or exact git commit, if installing from the repo)?

**Comment by fossouo** [comment]
jupyterhub : download from github and build wheel 
spawner : 0.2.0.dev-py3-none-any.whl (i download from github/jupyterhub/sudospawner)

I try to install those wheel on a server (without internet access)

**Comment by minrk** [comment]
Arg, sudospawner is *by far* the hardest to configure and debug. Can you test jupyter/sudospawner#14 with config:

```python
import logging
c.SudoSpawner.debug_mediator = True
c.JupyterHub.log_level = logging.DEBUG
```

**Comment by fossouo** [comment]
Sorry where should i set this ?

**Comment by minrk** [comment]
Sorry. Config goes in your `jupyterhub_config.py`.

**Comment by fossouo** [comment]
Sorry seems that the error come from my Anaconda version strange never seen it before i switch with a fresh version of Anaconda3-2.4.1-Linux-x86_64.sh . 
Sorry how do you install configurable-http-proxy without internet , i already tried npm pack no success.

**Comment by minrk** [comment]
You can use [npmbox](https://www.npmjs.com/package/npmbox) to build offline installers of npm packages.

**Comment by fossouo** [comment]
Oh thank you , i tried with offline-npm but npmbox seems a bit simple. 
Best Regards

**Comment by mohanamurali7** [comment]
Though, the issue is closed, just thought of adding the instructions I had followed to install Jupyterhub along with configurable-http-proxy without using npm installs.  Could do everything with the help of conda (Thanks to the conda - as it can get and install all the needed packages... even non Python packages. ) I have put the details in the following link:
https://mohanamuraligurunathan.blogspot.in/2018/04/jupyterhub-offline-install-without.html
