### ISSUE TITLE
Automatically expire JupyterHub and single-user server cookies at configurable intervals

### ISSUE THREAD

**Issue by ssanderson** [jupyter/jupyterhub#154]
Right now, once a user has logged in to their single-user server, they're considered validated forever unless they log out.  In particular, even if their hub token is revoked, the single-user server never learns about this fact because it happily accepts their existing single-user token.

I think the obvious fix for this is to set PeriodicCallbacks that purge token caches.  It might also make sense to set TTL values for the tornado cookies themselves.

**Comment by minrk** [comment]
Makes sense

**Comment by minrk** [comment]
Since this will require adding an expiry to each token in the db, it's a great time to explore alembic for db migration. I've been waiting for a db change to do that.
