### ISSUE TITLE
`cleanup` doesn't fire when process is killed by SIGTERM

### ISSUE THREAD

**Issue by ssanderson** [jupyter/jupyterhub#174]
This is documented behavior for the `atexit` module, but since SIGTERM is meant to be used for graceful shutdown, I'd expect the hub to exit gracefully on receipt of a TERM.  I assume fixing this is just a matter of registering a SIGTERM handler, but I'm not sure if there are complications with the tornado eventloop.

**Comment by minrk** [comment]
@ssanderson shouldn't be more complications than SIGINT. #176
