### ISSUE TITLE
Build & package

### ISSUE THREAD

**Issue by YannBrrd** [jupyter/jupyterhub#186]
Hi,

Can you provide a small guide to build & package (light, like tgz) jupytherhub to build it on some machine and have it run somewhere else ? 

Cheers,
Yann

**Comment by minrk** [comment]
@YannBrrd including dependencies, or not? If including dependencies, wheels are the way to go. But to package JupyterHub *itself*, should be the same as every other Python package:

    python setup.py sdist # or bdist_wheel, etc.

On the build system, you will need npm installed to build the package, but you will not need to run any npm commands yourself.

On the target system, you will need to install configurable-http-proxy, which is an npm package, and installable with:

    npm install -g configurable-http-proxy

If you can't run npm with network access on the destination (hopefully not the case), I think you can use [npmbox](https://github.com/arei/npmbox) to install the proxy. I have never done this.

## How I would do it

This is how I would actually do it (nodejs-legacy is a weird thing on debian/ubuntu, not necessary on all systems):

On the build system:

```bash
apt-get install npm
# nodejs-legacy is only needed on some debian/ubuntu systems to make npm work
apt-get install nodejs-legacy
git clone https://github.com/jupyter/jupyterhub.git
cd jupyterhub
pip wheel . "ipython[notebook]"
# the ipython[notebook] bit is unnecessary if you are running single-user servers in a different environment from the Hub itself
```

This will create a `wheelhouse` directory containing JupyterHub and all of the Python dependencies, including those of the single-user server. For the next step, I'll assume you have moved the wheelhouse to the deployment machine at `/srv/wheelhouse`. On the deployment machine:

```bash
# install JupyterHub, single-user server:
pip install -f /srv/wheelhouse /srv/wheelhouse/jupyterhub*.whl "ipython[notebook]"

# get the proxy:
apt-get install npm # (probably also nodejs-legacy)
npm install -g configurable-http-proxy
```

**Comment by YannBrrd** [comment]
Hi,

Thanks, I'll give it a shot. My point is to have a package with dependencies to deliver something runnable to ops teams...

Cheers,
Yann

**Comment by minrk** [comment]
Yup, it's a standard Python package and a standard npm package, which I think should be quite manageable.
