### ISSUE TITLE
Error with sudospawner

### ISSUE THREAD

**Issue by YannBrrd** [jupyter/jupyterhub#192]
Hi,

I'm trying to run jupyterhub with sudospawner. I installed anaconda 3 in /opt and jupyterhub from source (Linux Mint 17.1). When I try to log in I get a 
```bash
[I 2015-03-16 15:54:55.634 JupyterHub web:1811] 304 GET /favicon.ico (127.0.0.1) 2.87ms
sudo: a password is required
```
If I set command to `ALL` it just does not find `sudospawner` anyway, which is strange as it is in the user path... 

If i run `sudo -l` :
```
Matching Defaults entries for rhea on Mac-yann:
    env_reset, mail_badpass,
    secure_path=/usr/local/sbin\:/usr/local/bin\:/usr/sbin\:/usr/bin\:/sbin\:/bin

User rhea may run the following commands on Mac-yann:
    (root) NOPASSWD: /usr/lib/linuxmint/mintUpdate/checkAPT.py
    (ALL) NOPASSWD: /opt/anaconda3/bin/sudospawner
```
Looks there is an issue with my config... Any tip ? 

Thanks.
Yann

**Comment by minrk** [comment]
It's possible that sudospawner isn't on the PATH for the sudo command. You may need to specify:

```python
c.SudoSpawner.sudospawner_path = '/opt/anaconda3/bin/sudospawner'
```

**Comment by YannBrrd** [comment]
OK, in fact I put /opt/anaconda3/bin in /etc/sudoers

```
Defaults	secure_path="/opt/anaconda3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
```

**Comment by minrk** [comment]
Great, glad it worked out. Getting the sudospawner up and running is very complicated. I didn't realize how complex it would be when I set out to do it.

**Comment by YannBrrd** [comment]
Indeed. Stuck at launching individual servers now

**Comment by albertoferna** [comment]
I'm in the same situation. Did you manage to get it working?
