### ISSUE TITLE
Add doc to help debug

### ISSUE THREAD

**Issue by YannBrrd** [jupyter/jupyterhub#199]
Hi,

How to configure jupyter_config.py to have the right debugging level ? 

I have a message saying users servers are slow to start (and they don't start at all), but no logs anywhere...

Thanks.
Yann

**Comment by minrk** [comment]
You can set `JupyterHub.log_level = 'DEBUG' to increase the amount of logging.

**Comment by YannBrrd** [comment]
OK, thanks. Then where to I find logs ? Only term ? Files somewhere?

**Comment by minrk** [comment]
It's only logging to the terminal.

**Comment by YannBrrd** [comment]
OK, will update wiki
