### ISSUE TITLE
Is it possible to interleave different languages statements using Jupyter?

### ISSUE THREAD

**Issue by fbrundu** [jupyter/jupyterhub#202]
Hi,
just had an idea, but I do not know if it is possible (or feasible to implement):
What about creating notebook with different interleaved languages? For instance, there are ongoing projects to allow interoperability between python and R (rpy), or python and Julia (https://github.com/astrieanna/madpug). 
It would be great to have a transparent management of different languages by the Jupyter notebook.
Is it already implemented, or would it be done in the future?

Thanks

**Comment by dsblank** [comment]
That got really complicated, and was decided that notebooks should really be in a single language.

However, you can of course have magics that allow cells to be in a different language, or een to switch languages.

There are examples of this kind of operation. ICalico (http://calicoproject.org/ICalico) took an existing system that allowed multi-languages and made a kernel out of it. However, we are moving away from that, breaking them into their own kernels.

**Comment by fbrundu** [comment]
Ok Thanks :)

**Comment by rpcoelho17** [comment]
How do you do that with magics?  For example in RStudio you can open an notebook that allows you to switch the cell language using:
```{r}
# R code here
```
```{python}
#Python code here
```
Is it possible to do the same in Jupyter?
