### ISSUE TITLE
Help: set home folder on multiuser jupyterhub

### ISSUE THREAD

**Issue by lucacerone** [jupyter/jupyterhub#203]
Dear all,
I have been opened a Jupyter account on a computer running Jupyterhub (multiuser).

Everything works just fine, the only thing is that when I open my notebook,
the files in $HOME are shown. I keep all my notebooks in %HOME/Documents/jupyter/notebooks

Is there a way to have jupyterhub open my session directly in that directory?

Is there any environment variable or user configuration file I can set to do it?

Thanks a lot for the help,

Cheers,
Luca

**Comment by minrk** [comment]
If you want it to affect all users, set `Spawner.notebook_dir = '~/Documents/jupyter/notebooks'` in your `jupyterhub_config.py`. If you want to just set the default for you, you can do that in your own `.ipython/profile_default/ipython_notebook_config.py` with:

    import os
    c.NotebookApp.notebook_dir = os.path.expanduser(' ~/Documents/jupyter/notebooks')

**Comment by tongda** [comment]
Hi, I am considering that we can add an option in the **Admin** page, which let user set their default notebook dir. What do you think?

**Comment by lucacerone** [comment]
thanks for the help @minrk but it didn't work for me.

I have logged out the ipython server, made the change (creating the file since it wasn't there)
when I logged in the directory was still HOME.

Cheers,
Luca

**Comment by amacfie** [comment]
Yeah this didn't work for me either.

**Comment by ixjlyons** [comment]
@amacfie Try putting the config lines above in the file `~/.jupyter/jupyter_notebook_config.py` instead.

**Comment by amacfie** [comment]
Tried it, no luck unfortunately. I'll update if I get more debug info.

**Comment by weimindong2016** [comment]
I have the same issue here on JupyterHub. Any solutions since Oct 2017?

**Comment by abalter** [comment]
This is related, right? https://github.com/jupyterhub/jupyterhub/issues/929

**Comment by zhouanbo** [comment]
Putting the config file at ~/.jupyter/jupyter_notebook_config.py worked for me.

**Comment by farzadz** [comment]
Using `c.Spawner.notebook_dir = '~/my/path'` in `jupyterhub_config.py` makes the launcher of jupyterlab to create new notebooks in `~/my/path` directory. However, when the user starts a new terminal the working directory of the terminal is `~`. Is there any way to change it to `my/path` instead? It differs from [this](https://github.com/jupyter/notebook/issues/1898) issue I think.
