### ISSUE TITLE
notebooks cannot connect to kernels when switching away from localhost

### ISSUE THREAD

**Issue by schmittc** [jupyter/jupyterhub#210]
Hi,

I'm trying to set up a jupyterhub server to which students should connect. 
So far everything went smoothly and I can run jupyterhub locally (i.e. access via localhost). 

However, when accessing from remote I can successfully log in and also start a notebook but this notebook only tells me that there is no connection to the kernel (Python 3).

I can see in the log that the kernel is started:

I 2015-03-24 15:04:43.355 schmi016 kernelmanager:85] Kernel started: 9219be7f-bd6f-4d06-af2a-040147301da2
[D 2015-03-24 15:04:43.355 schmi016 kernelmanager:86] Kernel args: {'cwd': '/net/fs01/vol/ma09/homes/schmi016'}

but somehow the communication between the kernel and the notebook fails (it works fine if I run the web browser on the same host as the jupyterhub process)

In the configuration file I have set the following:

c.JupyterHub.hub_ip = 'hostname'

I suppose there is another config option that I'm missing that enables the communication between the notebook and the kernel when accessing from other hosts than localhost?

**Comment by schmittc** [comment]
One more comment: if I tell the notebook to reconnect to the kernel I see the following messages in the log file of jupyterhub:

16:02:41.319 - debug: [ConfigProxy] PROXY WEB /user/schmi016/api/kernels/9219be7f-bd6f-4d06-af2a-040147301da2?_=1427205880279 to http://localhost:49799
[D 2015-03-24 16:02:41.322 schmi016 log:47] 200 GET /user/schmi016/api/kernels/9219be7f-bd6f-4d06-af2a-040147301da2?_=1427205880279 (127.0.0.1) 1.14ms

but as I said the connection doesn't work

**Comment by dsblank** [comment]
Could be a permission issue. There is a section here:

https://github.com/jupyter/jupyterhub/wiki/Using-sudo-to-run-JupyterHub-without-root-privileges#linux

that describes having to allow node access to port 80 via:
```
sudo setcap 'cap_net_bind_service=+ep' /usr/bin/node
```
If not that, can you provide your config or command-line start flags?

**Comment by schmittc** [comment]
For testing purposes I am running the process as root:

sudo jupyterhub --config=/usr/local/etc/jupyterhub.py 

and here is the config:

schmi016@etap4:/tmp$ cat /usr/local/etc/jupyterhub.py |grep -v '#'|grep c
c = get_config()
c.JupyterHub.ssl_cert = '/usr/local/share/ca-certificates/ca.pem'
c.JupyterHub.hub_ip = 'my.host.de'
c.JupyterHub.admin_users = set(['schmi016'])
c.JupyterHub.debug_proxy = True
c.JupyterHub.port = 8888
c.JupyterHub.log_level = 'DEBUG'
c.JupyterHub.ssl_key = '/usr/local/share/ca-certificates/ca.key'
c.Spawner.debug = True
c.LocalProcessSpawner.debug = True

**Comment by dsblank** [comment]
(This is beyond my abilities, but I wonder if it works without SSL.)

**Comment by schmittc** [comment]
Thanks!!!

Indeed it works without ssl! Unfortunately having the students send their password unencrypted over the net is not something nice and that's why I had enabled ssl.

**Comment by minrk** [comment]
@schmittc is it a proper, trusted cert, or is it self-signed? If it's self-signed, there's a known issue where some browsers (Safari) refuse to make websocket connections, which would manifest as something similar to what you describe - everything working until you try to connect to a kernel.

**Comment by schmittc** [comment]
Indeed it's a self-signed certificate. Using Firefox instead of Safari works like a charm!

Thanks a lot!
