### ISSUE TITLE
Admin Panel - Last seen column includes shutdown activity

### ISSUE THREAD

**Issue by rgbkrk** [jupyter/jupyterhub#224]
The "Last Seen" column includes shutdown activity. I'm assuming this is an artifact of the proxy itself, but is a bit misleading. After shutting down several servers from users that had not been back in days, I noticed they all came up as visiting recently.

**Comment by minrk** [comment]
What do you mean by shutdown activity? How are you shutting them down?

**Comment by rgbkrk** [comment]
I clicked "stop server" for each of the users.

**Comment by minrk** [comment]
Gotcha. Stopping a server was unconditionally updating the last_activity field for that user. See #226.
