### ISSUE TITLE
Admin panel - Add ability to import multiple users at once

### ISSUE THREAD

**Issue by rgbkrk** [jupyter/jupyterhub#225]
It would be nice to add a list of users as a bulk list of newline delimited users.

**Comment by minrk** [comment]
Like the userlist file used in a few examples?

**Comment by rgbkrk** [comment]
Yeah, pretty much. We added a whole workshop class to demohub.

**Comment by minrk** [comment]
Hm. I'd like to push a little against adding web UI for everything. That would be an easy operation from a script, for instance.

**Comment by jhamrick** [comment]
I agree that we shouldn't add a web UI for everything, but I think in this case it would be nice to have this, as there already is an "add user" option. It seems like it wouldn't be too hard to change it from just a single-line text box to a multiline text box where usernames are separated by newlines.

**Comment by minrk** [comment]
That's true - and the admin checkbox can be used for admin, so the space-separated format of the userlist file is unnecessary.

That should be easy enough.

**Comment by fperez** [comment]
newlines, commas or spaces, any delimiter would work if it's just usernames for now. If we later want to allow username + first/last, then perhaps better to define the delimiter as newline, so further parsing can be done on the individual field.

It's a common enough thing to want that I'm +1 on that bit of UI at least.

**Comment by minrk** [comment]
#250

**Comment by fperez** [comment]
Closed by #250.
