### ISSUE TITLE
This webpage has a redirect loop when logging in.

### ISSUE THREAD

**Issue by rantaoca** [jupyter/jupyterhub#229]
I installed the server and ran it for the first time. The login screen showed up and when I tried to log in, I get a redirect loop. When I restart the server and go to the /hub, there isn't any redirect loop, and it gives me the page with "My Server" and "Admin". However, when I click the "My Server" link, it gives me the redirect loop again. I can still use the notebook if I point my browser to `http://localhost:58737/user/rantaoca`. I feel like this is a similar to issue https://github.com/jupyter/jupyterhub/issues/58.

I'm using jupyterhub release 0.10. When I run `which -a jupyterhub-singleuser` I get 
`/usr/local/bin/jupyterhub-singleuser`

Here's the debug output when I run with `--debug`.

```
[D 2015-04-12 17:18:25.156 JupyterHub application:242] Config changed:
[D 2015-04-12 17:18:25.156 JupyterHub application:243] {'JupyterHub': {'log_level': 10}}
[I 2015-04-12 17:18:25.157 JupyterHub app:515] Loading cookie_secret from /Users/rantaoca/Programs/jupyterhub/jupyterhub_cookie_secret
[D 2015-04-12 17:18:25.159 JupyterHub app:542] Connecting to db: sqlite:///jupyterhub.sqlite
[W 2015-04-12 17:18:25.233 JupyterHub app:251] 
    Generating CONFIGPROXY_AUTH_TOKEN. Restarting the Hub will require restarting the proxy.
    Set CONFIGPROXY_AUTH_TOKEN env or JupyterHub.proxy_auth_token config to avoid this message.
    
[I 2015-04-12 17:18:25.244 JupyterHub app:608] Not using whitelist. Any authenticated user will be allowed.
[D 2015-04-12 17:18:25.247 JupyterHub app:684] Loaded users: 
    rantaoca admin
[I 2015-04-12 17:18:25.270 JupyterHub app:743] Starting proxy @ http://*:8000/
[D 2015-04-12 17:18:25.270 JupyterHub app:744] Proxy cmd: ['configurable-http-proxy', '--ip', '', '--port', '8000', '--api-ip', 'localhost', '--api-port', '8001', '--default-target', 'http://localhost:8081']
17:18:25.517 - info: [ConfigProxy] Proxying http://*:8000 to http://localhost:8081
17:18:25.524 - info: [ConfigProxy] Proxy API at http://localhost:8001/api/routes
[D 2015-04-12 17:18:25.602 JupyterHub app:772] Proxy started and appears to be up
[I 2015-04-12 17:18:25.604 JupyterHub app:1008] Hub API listening on http://localhost:8081/hub/
[I 2015-04-12 17:18:32.001 JupyterHub log:100] 302 GET /hub/ (rantaoca@::1) 6.82ms
[I 2015-04-12 17:18:32.114 JupyterHub log:100] 200 GET /hub/home (rantaoca@::1) 106.86ms
[D 2015-04-12 17:18:32.243 JupyterHub log:100] 200 GET /hub/static/js/home.js?v=(%2720150412171825%27,) (@::1) 32.73ms
[D 2015-04-12 17:18:32.367 JupyterHub log:100] 200 GET /hub/static/components/jquery/jquery.min.js?v=(%2720150412171825%27,) (@::1) 41.27ms
[D 2015-04-12 17:18:32.372 JupyterHub log:100] 200 GET /hub/static/js/jhapi.js?v=(%2720150412171825%27,) (@::1) 3.68ms
[D 2015-04-12 17:18:32.444 JupyterHub log:100] 200 GET /hub/static/js/utils.js?v=(%2720150412171825%27,) (@::1) 3.85ms
[I 2015-04-12 17:18:35.159 JupyterHub spawner:352] Spawning jupyterhub-singleuser --user=rantaoca --port=58737 --cookie-name=jupyter-hub-token-rantaoca --base-url=/user/rantaoca --hub-prefix=/hub/ --hub-api-url=http://localhost:8081/hub/api --ip=localhost
[D 2015-04-12 17:18:35.166 JupyterHub spawner:219] Polling subprocess every 30s
[I 2015-04-12 17:18:36.720 rantaoca notebookapp:633] Using MathJax from CDN: https://cdn.mathjax.org/mathjax/latest/MathJax.js
[I 2015-04-12 17:18:36.815 rantaoca notebookapp:1066] Serving notebooks from local directory: /Users/rantaoca
[I 2015-04-12 17:18:36.815 rantaoca notebookapp:1066] 0 active kernels 
[I 2015-04-12 17:18:36.815 rantaoca notebookapp:1066] The IPython Notebook is running at: http://localhost:58737/user/rantaoca/
[I 2015-04-12 17:18:36.815 rantaoca notebookapp:1067] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 2015-04-12 17:18:36.981 rantaoca log:47] 302 GET /user/rantaoca (::1) 2.39ms
[D 2015-04-12 17:18:36.983 JupyterHub utils:73] Server at http://localhost:58737/user/rantaoca responded with 302
[I 2015-04-12 17:18:36.984 JupyterHub base:229] User rantaoca server took 1.867 seconds to start
[I 2015-04-12 17:18:36.984 JupyterHub orm:169] Adding user rantaoca to proxy /user/rantaoca => http://localhost:58737
[D 2015-04-12 17:18:36.987 JupyterHub orm:156] Fetching POST http://localhost:8001/api/routes/user/rantaoca
[I 2015-04-12 17:18:37.012 JupyterHub log:100] 302 GET /hub/user/rantaoca/ (rantaoca@::1) 1891.79ms
[I 2015-04-12 17:18:37.019 JupyterHub log:100] 302 GET /user/rantaoca/ (@::1) 0.91ms
[I 2015-04-12 17:18:37.030 JupyterHub log:100] 302 GET /hub/user/rantaoca/ (rantaoca@::1) 5.23ms
[I 2015-04-12 17:18:37.035 JupyterHub log:100] 302 GET /user/rantaoca/ (@::1) 0.73ms
[I 2015-04-12 17:18:37.051 JupyterHub log:100] 302 GET /hub/user/rantaoca/ (rantaoca@::1) 8.09ms
... (continues to redirect) ...
```

**Comment by minrk** [comment]
That looks like you've visited the wrong port. You should only access the Hub through the proxy (on port :8000 in your case). Are you visiting port 8081 instead?

**Comment by rantaoca** [comment]
Ah you're completely right! I was trying to access it on port 8081, port 8000 works perfectly. Thank you so much.

**Comment by minrk** [comment]
@rantaoca this has happened a few times, and I'd like to avoid it. What gave you the impression that you should visit port 8081?

**Comment by rantaoca** [comment]
I'm not very good at following directions :) I followed the README instructions, and after the step where I run jupyter, I thought I could figure out which port it was based on the console output.

When the jupyterhub server starts, the last line in the console output is:
`Hub API listening on http://localhost:8081/hub/`

If this is confusing people other than me, then maybe there could be a console "splash screen" that gets displayed when the hub finishes starting up?

**Comment by minrk** [comment]
Yup, I'll try to make sure the last URL in the console is the right one. Thanks.

**Comment by franciscovargas** [comment]
I believe I am having the same issue I have no bugs when running debug but I dont know how to visit the right port. If I visit http://localhost:8080 page is not found

**Comment by thongnnguyen** [comment]
Hello, can we reopen this issue, because I think have the same problem. But in my case, localhost:8000 actually does not work at all.

I follow the tutorial at this link: https://www.youtube.com/watch?v=gSVvxOchT8Y&feature=youtu.be

When launching jupyterhub (the user is 'thong'), I'm in directory `~/thong/Installer/jupyterhub-tutorial`, in which I have a `jupyterhub_config.py` generated and just has the following

`
c.Spawner.default_url = '/lab'#default to jupyterlab
#SSL
c.JupyterHub.ssl_key = '/etc/letsencrypt/live/thong.mynetgear.com/privkey.pem'
c.JupyterHub.ssl_cert = '/etc/letsencrypt/live/thong.mynetgear.com/fullchain.pem'
`
This is what I get from the terminal

`
(jupyterhub-tutorial) thong@thong-server:~/Installer/jupyterhub-tutorial$ jupyterhub
[I 2018-03-25 21:20:02.616 JupyterHub app:724] Loading cookie_secret from /home/thong/Installer/jupyterhub-tutorial/jupyterhub_cookie_secret
[W 2018-03-25 21:20:02.665 JupyterHub app:365]
    Generating CONFIGPROXY_AUTH_TOKEN. Restarting the Hub will require restarting the proxy.
    Set CONFIGPROXY_AUTH_TOKEN env or JupyterHub.proxy_auth_token config to avoid this message.

[W 2018-03-25 21:20:02.671 JupyterHub app:864] No admin users, admin interface will be unavailable.
[W 2018-03-25 21:20:02.671 JupyterHub app:865] Add any administrative users to `c.Authenticator.admin_users` in config.
[I 2018-03-25 21:20:02.671 JupyterHub app:892] Not using whitelist. Any authenticated user will be allowed.
{'trait': <traitlets.traitlets.Unicode object at 0x7f0c77093c18>, 'value': '/lab', 'owner': <jupyterhub.spawner.LocalProcessSpawner object at 0x7f0c76575588>}
[W 2018-03-25 21:20:02.687 JupyterHub app:1097] thong not running.
[I 2018-03-25 21:20:02.861 JupyterHub app:1453] Hub API listening on http://127.0.0.1:8081/hub/
[I 2018-03-25 21:20:02.866 JupyterHub app:1176] Starting proxy @ http://*:8000/
21:20:03.189 - info: [ConfigProxy] Adding route / -> http://127.0.0.1:8081
21:20:03.213 - info: [ConfigProxy] Proxying https://*:8000 to http://127.0.0.1:8081
21:20:03.213 - info: [ConfigProxy] Proxy API at http://127.0.0.1:8001/api/routes
[I 2018-03-25 21:20:03.278 JupyterHub app:1485] JupyterHub is now running at http://127.0.0.1:8000/
`

Attached are what appears when I access localhost:8000 and localhost:8081.

Is there any idea where I did wrong?

Thank you very much
![access-port8081](https://user-images.githubusercontent.com/22683365/37884233-8e082344-3074-11e8-8a65-36a599372e8a.png)
![access-port8000](https://user-images.githubusercontent.com/22683365/37884237-91ed462e-3074-11e8-97cc-ca347fb132b0.png)

**Comment by minrk** [comment]
Visiting `localhost:8081` will never work and should never be tried. If you get a redirect loop on the regular login page, there can be a host of reasons. One is that the single-user servers are running the wrong version. What Spawner are you using? Can you include the logs of `jupyterhub --debug` during the time of the redirects (there will be a log statement for every redirect).

**Comment by ma010** [comment]
I am in the same situation as @thongnnguyen. Here is the output from --debug mode.
```
$ sudo jupyterhub -f /etc/jupyterhub/jupyterhub_config.py --debug
[D 2019-01-03 11:12:35.711 JupyterHub application:555] Looking for /etc/jupyterhub/jupyterhub_config in /Users/nathan/data-science/tutorials
[D 2019-01-03 11:12:35.712 JupyterHub application:577] Loaded config file: /etc/jupyterhub/jupyterhub_config.py
[I 2019-01-03 11:12:35.713 JupyterHub app:1673] Using Authenticator: dummyauthenticator.dummyauthenticator.DummyAuthenticator
[I 2019-01-03 11:12:35.713 JupyterHub app:1673] Using Spawner: jupyterhub.spawner.LocalProcessSpawner-0.9.4
[I 2019-01-03 11:12:35.720 JupyterHub app:1016] Loading cookie_secret from /Users/nathan/data-science/tutorials/jupyterhub_cookie_secret
[D 2019-01-03 11:12:35.720 JupyterHub app:1071] Connecting to db: sqlite:///jupyterhub.sqlite
[D 2019-01-03 11:12:35.742 JupyterHub orm:685] database schema version found: 896818069c98
[I 2019-01-03 11:12:35.746 JupyterHub proxy:431] Generating new CONFIGPROXY_AUTH_TOKEN
[D 2019-01-03 11:12:35.778 JupyterHub app:1473] Loading state for nathan from db
[D 2019-01-03 11:12:35.781 JupyterHub app:1489] Loaded users:
      nathan admin
[I 2019-01-03 11:12:35.788 JupyterHub app:1855] Hub API listening on http://127.0.0.1:8081/hub/
[I 2019-01-03 11:12:35.789 JupyterHub proxy:567] Starting proxy @ http://127.0.0.1:8000/
[D 2019-01-03 11:12:35.789 JupyterHub proxy:568] Proxy cmd: ['configurable-http-proxy', '--ip', '127.0.0.1', '--port', '8000', '--api-ip', '127.0.0.1', '--api-port', '8001', '--error-target', 'http://127.0.0.1:8081/hub/error', '--ssl-key', '/Users/nathan/.ssh/key.pem', '--ssl-cert', '/Users/nathan/.ssh/server.crt']
[D 2019-01-03 11:12:35.793 JupyterHub proxy:517] Writing proxy pid file: jupyterhub-proxy.pid
11:12:36.309 - info: [ConfigProxy] Proxying https://127.0.0.1:8000 to (no default)
11:12:36.312 - info: [ConfigProxy] Proxy API at http://127.0.0.1:8001/api/routes
[D 2019-01-03 11:12:36.899 JupyterHub proxy:603] Proxy started and appears to be up
[D 2019-01-03 11:12:36.899 JupyterHub proxy:296] Fetching routes to check
[D 2019-01-03 11:12:36.901 JupyterHub proxy:686] Proxy: Fetching GET http://127.0.0.1:8001/api/routes
[I 2019-01-03 11:12:36.914 JupyterHub proxy:301] Checking routes
[I 2019-01-03 11:12:36.914 JupyterHub proxy:370] Adding default route for Hub: / => http://127.0.0.1:8081
[D 2019-01-03 11:12:36.914 JupyterHub proxy:686] Proxy: Fetching POST http://127.0.0.1:8001/api/routes/
[I 2019-01-03 11:12:36.916 JupyterHub app:1912] JupyterHub is now running at http://127.0.0.1:8000/
[D 2019-01-03 11:17:36.905 JupyterHub proxy:686] Proxy: Fetching GET http://127.0.0.1:8001/api/routes
[I 2019-01-03 11:17:36.912 JupyterHub proxy:301] Checking routes
```
I am using the default spawner (Using Spawner: jupyterhub.spawner.LocalProcessSpawner-0.9.4). @minrk
