### ISSUE TITLE
Single user server cannot be run under Python 2

### ISSUE THREAD

**Issue by ssanderson** [jupyter/jupyterhub#235]
While the majority of JupyterHub's codebase is Python 3 only, the single user server is an extension to the core Jupyter Notebook, which still supports Python 2 to the best of my knowledge.  

80531341c052fb8bc6bab5c3aaaac0b6329b03d2 renders the Single user server unusable in Python 2 because it imports from `urllib.parse`, which only exists in Python 3.  Since the message associated with that commit is "make the single user server run on Python 3 **by default**", I assume that making the single user server entirely incompatible with Python 2 is unintentional?

**Comment by minrk** [comment]
I think it's fine for the single-user server to require Python 3. It's only kernel code that needs to run on py2, and that's unaffected by the server Python.

**Comment by ssanderson** [comment]
The issue here for me is that I'm running the single user server in a docker container.  Forcing the single-user server to run on Python means that I have to supply both Python 2 and Python 3 in said container, which makes my build times substantially longer and makes my substantially container larger, which means slower deploys and new failure modes.

**Comment by ssanderson** [comment]
@minrk https://github.com/jupyter/jupyterhub/pull/236 makes singleuser.py runnable again for me under Python 2.  

I'm 100% on board with the main hub code only supporting Python 3, but forcing users to run single-user servers under Python 3 as well represents a substantial burden for anyone who only plans to supply Python 2 kernels.

**Comment by minrk** [comment]
The notebook server that single-user subclasses probably won't keep Python 2 support too much longer, specifically because the server and kernel don't need to use the same Python.
