### ISSUE TITLE
Add pyzmq and jsonschema to requirements

### ISSUE THREAD

**Issue by eyalzek** [jupyter/jupyterhub#247]
After installing the requirements and jupyterhub, I tried logging in using the web interface and it was loading forever, looking at the terminal I saw ImportErrors for zmq (which I had to install) and after that I got the same for jsonschema.

Installing both enabled me to run the server properly.

**Comment by minrk** [comment]
Hm, it shouldn't depend on either. I think it's some imports from IPython.html that should probably be removed.
