### ISSUE TITLE
Unable to log in to server launched from admin panel 

### ISSUE THREAD

**Issue by rgbkrk** [jupyter/jupyterhub#249]
This has me a bit flummoxed so I'm just going to list the steps that led to getting to a 500 error.

1. Logged in to the demo jupyter hub
2. Clicked admin
3. Started my own notebook server using "start server" on the admin panel
4. Clicked the jupyter logo in the corner
5. Get redirected to `/user/rgbkrk/tree`
6. Following error pops up

```
500 : Internal Server Error
The error was:
Failed to check authorization
```

At this point I'm unable to visually navigate anywhere to log out. Going to the base URL redirects me to my server.

To get around this, I typed in the path for the admin panel and then clicked logout. After logging back in it was just fine.

**Comment by minrk** [comment]
This is exactly the problem with trying to hide the Hub, and redirecting to the single-user server under more circumstances. It was what I did initially, then ran into problems like this and changed it to be more explicit, if tedious. At the request of others, I changed it back, reintroducing all the earlier problems.

**Comment by minrk** [comment]
What do you see in the logs (it logs more details about failed authentication than it shows the user)? Are you running latest master? What deployment? What authenticator, spawner, etc.?

**Comment by rgbkrk** [comment]
This was on demohub.jupyter.org

**Comment by minrk** [comment]
ok, I'll dig into the logs there.

**Comment by minrk** [comment]
Ah, it's because JupyterHub has been updated but the single-user containers are still on an old version. I need to destroy and recreate all the single-user containers.
