### ISSUE TITLE
output cells not being printed when using anaconda-based kernel

### ISSUE THREAD

**Issue by shreddd** [jupyter/jupyterhub#254]
I was successfully able to get a python2 kernel running inside jupyterhub using a version of python built from source. I installed the kernel with: `/usr/local/bin/ipython2 kernelspec install-self`
This seems to work and displays output cells in the notebook.

However when I try the same thing with an anaconda installation it doesn't seem to print output cells in the ipython notebook. Here is what I did:
`/anaconda/bin/ipython kernelspec install-self`

Any idea why an anaconda-based python does not display output cells? Is there something additional I need to do with the kernel installer?

Here is the kernel.json file
```json
{
 "display_name": "Python 2 (Anaconda)",
 "language": "python",
 "argv": [
  "/anaconda/bin/python",
  "-m",
  "IPython.kernel",
  "-f",
  "{connection_file}"
 ]
}
```

**Comment by shreddd** [comment]
Any updates on this? As I mentioned earlier, this works when I simply replace "/anaconda/bin/python" with "/usr/local/bin/python" ... is there a way to debug a kernel and whether it is properly writing things back to the server? 

Note that I am able to attach to the existing kernel using:
```
/anaconda/bin/ipython console --existing kernel-6c5d90dd-8853-448c-851e-1d6fd01fad5f.json
```
and it does seem to pick up the commands and variables set within the notebook. So there seems to be a communications issue with sending stuff back to the notebook server. 

Any tips on how to diagnose this would be extremely helpful.

**Comment by minrk** [comment]
Do you see anything different when you try to do this without JupyterHub? Just a regular notebook server?

**Comment by shreddd** [comment]
Just checked - Same problem with a regular notebook server.

**Comment by minrk** [comment]
Fixed in person: Problem was the nbserver had zeromq 2.2, the kernel had 4.0.5.

**Comment by StephenElston** [comment]
I am having what sounds like the same problem running locally. I am  new to Jupyter so I don't understand what the solutions means. Can you please explain in a bit more detail.

**Comment by minrk** [comment]
@StephenElston how did you install things? The thing to check is the version of libzmq:

```bash
/path/to/python -c 'import zmq; print("pyzmq-%s, libzmq-%s" % (zmq.__version__, zmq.zmq_version()))'
```

For the Python that you see in `head -n $(which jupyter-notebook)` and in your kernelspecs.

If you see any `libzmq-2` in there, you probably need to reinstall pyzmq for that Python:

    /path/to/python -m pip uninstall pyzmq
    /path/to/python -m pip install pyzmq --install-option="--zmq=bundled"

**Comment by StephenElston** [comment]
Thanks for your help. In the end I think my problem was having an incorrect PATH variable. Everything is working great now!
