### ISSUE TITLE
doesnt't find the terminado module, avoiding to use terminals

### ISSUE THREAD

**Issue by miguelalexanderdiaz** [jupyter/jupyterhub#272]
I'm running JupyterHub with anaconda in a separated environment , we use a lot the terminal tool of Jupyter, but appear to be unavailable when I launch JupyterHub in debug mode returns the following message.
 
>[W 2015-07-11 11:54:20.026 machitivad notebookapp:915] Terminals not available (error was No module named 'terminado')

That is weird because I already installed terminado, and when I run ipython notebook without jupyterhub, is working normally, I can't figure out how force to jupyterhub to use the terminado module that I already installed in my environment.

Hope you can help me

(I'm using ubuntu 14.04, python 3.3.5, terminado 0.5  )

**Comment by minrk** [comment]
Usually it's a matter of paths and pythons not being what you expect. How did you install terminado? Is `sys.executable` what you expect it to be in the notebook?

**Comment by miguelalexanderdiaz** [comment]
I installed terminado via anaconda, the ideal for me is that when I launch jupyterhub takes the python of anaconda, instead of  the installed in the OS.

When I look at `sys.executable` (using the notebook) I get this:

**Python2**
>/opt/anaconda/envs/mindlabenv/bin/python

**Python3**
>/usr/bin/python3

obviously in the case of *python3* is using the wrong python binaries, but I wonder if exist some config trick to execute jupyterhub pointing directly to the python that is hosted in anaconda

**Comment by miguelalexanderdiaz** [comment]
Well I get around of the issue and I can solve it by my own. I create another anaconda env and reinstall jupyterhub in that new env from scratch, copy the config files and all works smoothly; apparently it was a problem with my first conda env and when I install jupyterhub by first time take the binary pythons of the OS instead of the enviroment.
