### ISSUE TITLE
Dead link in privileges documentation

### ISSUE THREAD

**Issue by claresloggett** [jupyter/jupyterhub#277]
At https://github.com/jupyter/jupyterhub/wiki/Using-sudo-to-run-JupyterHub-without-root-privileges , there are instructions on making the shadow password database readable by the JupyterHub process on Linux.

The gist link in "However, you may want to further understand the consequences of this. See: https://gist.github.com/gadr/6389682" appears to be a dead link.

**Comment by minrk** [comment]
Link removed, thanks. I guess this is the vulnerability of wiki docs.
