### ISSUE TITLE
base_url is used twice in redirects

### ISSUE THREAD

**Issue by Xarthisius** [jupyter/jupyterhub#280]
For  jupyterhub running at *http://address/prefix/* almost every redirect has `base_url` twice. It was caused by PR #276. Reverting changes to jupyterhub/handlers/pages.py:27 [1] fixes the issue.

[1] https://github.com/Crunch-io/jupyterhub/commit/05e4ab41fe6691dd697eecc27d9abee2ac4e23b6

**Comment by minrk** [comment]
Thanks, should be fixed now.
