### ISSUE TITLE
path completion

### ISSUE THREAD

**Issue by kehey** [jupyter/jupyterhub#283]
Can the path completion with tab be changed so that you do not always see the complete path so far in the pop-up, but only the further options? With long paths, the end of the path (which then contains the files I need to choose from) fall off the screen or I have to start scrolling.

**Comment by minrk** [comment]
Hi, can you reopen this on the [jupyter/notebook](https://github.com/jupyter/notebook) repo? JupyterHub is specifically the multi-user wrapper for notebook servers. And I would call it a general issue for long completions, with paths as a specific common case. Thanks!
