### ISSUE TITLE
Setting JupyterHub.hub_prefix and JupyterHub.base_url Causes 404s

### ISSUE THREAD

**Issue by brunobeltran** [jupyter/jupyterhub#289]
On login, the url that the user is redirected to appears to be `$base_url/$hub_prefix`. Sorry for the noise if this is intended behavior, but something is definitely fishy.

For example, say I would like to put the whole application at `/lenovo/jupyterhub/`, and the hub at `/lenovo/jupyterhub/hub/`. I'm not a web developer, so I'm not sure whether the correct answer is to set 
`$base_url = '/lenovo/jupyterhub/'` and `$hub_prefix = '/hub/'`
or 
`$base_url = '/lenovo/jupyterhub/'` and `$hub_prefix = '/lenovo/jupyterhub/hub/'`
but neither work, and it's not clear from trying to explore how the default URL rewriting works what was the intended behavior.

For example, with `$base_url = '/lenovo/jupyterhub/'` and `$hub_prefix = '/hub/'`, then if I'm logged in via PAM as bbeltr1, the only URL that forwards correctly is `/hub/user/bbeltr1`

`https://localhost/hub/user/bbeltr1`

redirects to

`https://localhost/lenovo/jupyterhub/user/bbeltr1/tree`

whereas, after whatever service that takes care of `/tree/` has spawned

`https://localhost/`

redirects to

`https://localhost/hub/lenovo/jupyterhub/user/bbeltr1`

and

`https://localhost/hub/`

redirects to the same URL,

`https://localhost/hub/lenovo/jupyterhub/user/bbeltr1`,

which of course does not exist.

On the other hand, with `$base_url = '/lenovo/jupyterhub/'` and `$hub_prefix = '/lenovo/jupyterhub/hub/'`, I get the behavior that I expect (`/lenovo/jupyterhub/hub/user/bbeltr1` forwards to `/lenovo/jupyterhub/user/bbeltr1/tree`), but (here's a weird one), `/lenovo/jupyterhub/user/bbeltr1` forwards to `/hub/eltr1` (sic).

**Comment by minrk** [comment]
Are you using latest master?

**Comment by brunobeltran** [comment]
I thought I was. Was not. Apologies.

**Comment by minrk** [comment]
Okay, thanks.
