### ISSUE TITLE
Self signed SSL cert, terminal, and safari

### ISSUE THREAD

**Issue by TDaltonC** [jupyter/jupyterhub#292]
I've set up a jupyter hub for some friends using a self signed certificate. When using sufari, terminals will not load and we get this console error:
```
[Error] WebSocket network error: OSStatus Error -9807: Invalid certificate chain
```

**Comment by minrk** [comment]
Yup, Safari refuses to make wss (websocket over https) connections when the cert isn't trusted. The only way is to explicitly trust the certificate. You can do this by adding the cert to you Keychain app, but each client machine has to do this. There isn't anything we can do about it, unfortunately.

**Comment by TDaltonC** [comment]
Thanks Min

**Comment by stevenmanton** [comment]
I just ran into this, too. Any chance this situation can be detected and a useful error message and resolution process displayed? Thanks for the solution!

**Comment by minrk** [comment]
We should be able to at least detect the case:

- ssl is used
- browser = safari
- websocket connection fails

I'm not sure if we can ask the browser if the certificate is untrusted, but that should get us close enough.

**Comment by mattdesl** [comment]
I was banging my head against a wall trying to fix this — it seems like Safari is the only browser that doesn't accept a self-signed untrusted certificate for secure WebSockets.

I fixed the cert like so:

- Make sure you're using SHA256 generating the self-signed key
- Make sure your CommonName is set to the same host (i.e. IP) you are running — you can use the command `-subj /CN=192.168.1.54`
- You need to send the `.cer` file to your phone and manually Install/Trust it (which adds it to `General > Profiles`)

I detailed the rest of the steps here for my use-case:
https://github.com/mattdesl/budo/blob/dcbc05866f583e172d6b46c898048436ab84ddae/docs/command-line-usage.md#ssl-on-ios
