### ISSUE TITLE
Installing in a non-standard prefix

### ISSUE THREAD

**Issue by noobermin** [jupyter/jupyterhub#293]
Hi, does Jupyter allow installing in a non-standard prefix? Passing `--install-option="--prefix=$PREFIX_DIR"` to pip has no effect on the attempted installation into a prefix.

**Comment by minrk** [comment]
Installation location is entirely up to pip. JupyterHub doesn't pick where it goes. Can you run pip with `-v` and show what happens? Does the same command work for other packages?

**Comment by Yurlungur** [comment]
I recommend telling pip to install in a nonstandard place using the ```--user``` flag with the ```PYTHONUSERBASE``` shell variable. For example:
```PYTHONUSERBASE=$PREFIX_DIR pip install --user jupyterhub```
This will probably produce an install path along the lines of
```$PREFIX_DIR/lib/python3.4/site-packages/jupyterhub```
for the module and
```$PREFIX_DIR/bin/jupyterhub```
for the executable.

This procedure worked for me, anyway. However, I should warn you that I had trouble when I tried to use the same $PREFIX_DIR for both python2 and python3 packages. I'd recommend either using only python3 or using some more sophisticated tool like virtualenvs or conda to handle mixed packages.

**Comment by noobermin** [comment]
I've had issues with `--user` in the past, but it does work for now.
