### ISSUE TITLE
Only primary group available in JupyterHub Terminal

### ISSUE THREAD

**Issue by mogthesprog** [jupyter/jupyterhub#299]
So. Basically, when I open  a jupyterhub terminal, I only have my primary group...

[morganj@cb0677f233db ~]$ groups  
Unix_Users  

However, my groups are available to me...

[morganj@cb0677f233db ~]$ groups
Unix_Users
[morganj@cb0677f233db ~]$ newgrp UNIX_AS_AN
[morganj@cb0677f233db ~]$ groups
UNIX_AS_AN             <------- (1)
[morganj@cb0677f233db ~]$ exit 
[morganj@cb0677f233db ~]$ newgrp UNIX_AS_AN
[morganj@cb0677f233db ~]$ newgrp Unix_Users
[morganj@cb0677f233db ~]$ groups 
Unix_Users UNIX_AS_AN     <---- (2)
[morganj@cb0677f233db ~]$ su adamho
Password: 
[adamho@cb0677f233db morganj]$ groups 
Unix_Users cm GROUP1 GROUP2 GROUP3 GROUP4 <----- (3)

Okay so at (1) we see I have one group. What's strange is that a newgrp command replaces my primary group. This isn't native linux behaviour. So something is a bit weird. Then if i issue a second newgrp command in subshell, the groups start appending. This is how newgrp is supposed to work (2).                    

And lastly, we see me using 'su' to change to another user (3).... And lo-and behold, We get all our groups back. I get the impression this is something to do with the terminal implementation in Jupyter.

**Comment by mogthesprog** [comment]
This is due to group enumeration in the host. And the way guids are read by jupyterhub. In sssd this is solvable with the "enumerate = true" flag.

I'll mark this closed.

**Comment by eburgueno** [comment]
@mogthesprog heya, sorry to revive this old issue. Were you using this against PAM authentication or LDAP authentication?

**Comment by mogthesprog** [comment]
This was all done with PAM Authentication. What are you trying to do and what errors/behaviour are you seeing? Also what version of jupyterhub are you using? :)

**Comment by eburgueno** [comment]
@mogthesprog We are running version `0.6.1` using the LDAP authenticator plugin with this config:

```
### LDAP Auth
c.JupyterHub.authenticator_class = 'ldapauthenticator.LDAPAuthenticator'
c.LDAPAuthenticator.server_address = '<ldap server>'
c.LDAPAuthenticator.bind_dn_template = 'uid={username},cn=users,cn=accounts,dc=ourdomain,dc=com'
c.LDAPAuthenticator.allowed_groups = [
        'cn=group1,cn=groups,cn=accounts,dc=ourdomain,dc=com',
        'cn=groupn,cn=groups,cn=accounts,dc=ourdomain,dc=com'
]
```

Based on [this code](https://github.com/jupyterhub/jupyterhub/blob/master/jupyterhub/spawner.py#L396), it seems to me that the spawner is not using the LDAP to retrieve the user groups. Rather, it's relying on the user groups reported by the OS. The only workaround is to allow LDAP users to authenticate to the server, which is not what we want.

Wondering if I should open a new issue for this.
