### ISSUE TITLE
Error installing configurable-http-proxy

### ISSUE THREAD

**Issue by nuwang** [jupyter/jupyterhub#303]
Hi,

I've been testing out JupyterHub on Openstack, and it's worked well, but as of today, the following error crops up when installing configurable-http-proxy.

Command:
"/usr/bin/nodejs" "/usr/bin/npm" "install" "--global" "configurable-http-proxy"

Error Log Extract:
```
npm http GET https://registry.npmjs.org/strftime/-/strftime-0.8.4.tgz
npm http 200 https://registry.npmjs.org/strftime/-/strftime-0.8.4.tgz
npm ERR! Error: shasum check failed for /root/tmp/npm-12521-fswefMRr/1442410163225-0.8111752143595368/tmp.tgz
npm ERR! Expected: 86b15949845e7de20c0c3d69db2b74fb73e4d25e
npm ERR! Actual:   da39a3ee5e6b4b0d3255bfef95601890afd80709
npm ERR!     at /usr/lib/nodejs/sha/index.js:38:8
npm ERR!     at ReadStream.<anonymous> (/usr/lib/nodejs/sha/index.js:85:7)
npm ERR!     at ReadStream.EventEmitter.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:920:16
npm ERR!     at process._tickCallback (node.js:415:13)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-63-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "--global" "configurable-http-proxy"
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
```
I've  retested this on Amazon EC2 with Ubuntu 14.04, and the same problem crops up. So I'm guessing there's some sort of package corruption? I've also tried building from source after upgrading the dependency on strftime from 0.8.4 to 0.9.2, which seems to solve the problem. Is there a possibility of getting the npm version fixed?

**Comment by nuwang** [comment]
This has resolved itself - so presumably, the node packages were repaired.

**Comment by jbrant** [comment]
Not for me - I get this with configurable-http-proxy installed.

**Comment by Muhammad-Imtiaz** [comment]
@nuwang hi, hope you will be find. I'm getting the following error when trying to run configurable http-proxy command on ubuntu 16.04. 

Command:npm install -g configurable-http-proxy
Error:
npm ERR! Linux 4.15.0-39-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "--global" "configurable-http-proxy"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ECONNRESET

npm ERR! network tunneling socket could not be established, cause=write EPROTO
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! Please include the following file with any support request:
npm ERR!     /home/imtiaz/npm-debug.log

Please reply me as soon as possible. This is barrier while running jupyterhub.
Thanks in advance.
