### ISSUE TITLE
Problem about run jupyterhub in Ubuntu 14.04

### ISSUE THREAD

**Issue by sakanamax** [jupyter/jupyterhub#308]
OS: Ubuntu 14.04
jupyterhub version: 0.2.0
python version : 3.4

Install jupyterhub by these commands
$ sudo apt-get update
$ sudo apt-get -y install python-pip python3-pip
$ sudo apt-get -y install python3-dev python-dev libzmq3-dev
$ sudo apt-get -y install npm nodejs-legacy
$ sudo npm install -g configurable-http-proxy
$ sudo pip3 install jupyterhub

I can install jupyterhub and start in ubuntu 14.04

$ sudo  jupyterhub
[I 2015-09-22 06:20:12.279 JupyterHub app:532] Writing cookie_secret to /users/maxhuang/jupyterhub_cookie_secret
[W 2015-09-22 06:20:12.948 JupyterHub app:257] 
    Generating CONFIGPROXY_AUTH_TOKEN. Restarting the Hub will require restarting the proxy.
    Set CONFIGPROXY_AUTH_TOKEN env or JupyterHub.proxy_auth_token config to avoid this message.
    
[I 2015-09-22 06:20:13.050 JupyterHub app:654] Not using whitelist. Any authenticated user will be allowed.
[I 2015-09-22 06:20:13.159 JupyterHub app:1032] Hub API listening on http://localhost:8081/hub/
[I 2015-09-22 06:20:13.168 JupyterHub app:789] Starting proxy @ http://*:8000/
06:20:13.471 - info: [ConfigProxy] Proxying http://*:8000 to http://localhost:8081
06:20:13.474 - info: [ConfigProxy] Proxy API at http://localhost:8001/api/routes
[I 2015-09-22 06:20:13.497 JupyterHub app:1055] JupyterHub is now running at http://localhost:8000/

I can  use username / password  login http://SERVERIP:8000

But when user login
just show "Your server is starting up.
You will be redirected automatically when it's ready for you."
![2015-09-22_4 18 45](https://cloud.githubusercontent.com/assets/5405809/10031955/afe23582-6145-11e5-98ce-d6aae4d2e7c9.png)

In the console, repeat 2 error messages

1.
Spawning jupyterhub-singleuser --user=opensuse --port=38969 --cookie-name=jupyter-hub-token-opensuse --base-url=/user/opensuse --hub-prefix=/hub/ --hub-api-url=http://localhost:8081/hub/api --ip=localhost
Traceback (most recent call last):
  File "/usr/local/bin/jupyterhub-singleuser", line 3, in <module>
    from jupyterhub.singleuser import main
  File "/usr/local/lib/python3.4/dist-packages/jupyterhub/singleuser.py", line 21, in <module>
    from IPython.utils.traitlets import (
ImportError: No module named 'IPython'

2.
[E 2015-09-22 06:23:45.225 JupyterHub gen:733] Exception in Future <tornado.concurrent.Future object at 0x7f927a3916a0> after timeout
    Traceback (most recent call last):
      File "/usr/local/lib/python3.4/dist-packages/tornado/gen.py", line 729, in error_callback
        future.result()
      File "/usr/local/lib/python3.4/dist-packages/jupyterhub/orm.py", line 418, in spawn
        raise e
      File "/usr/local/lib/python3.4/dist-packages/jupyterhub/orm.py", line 394, in spawn
        yield self.server.wait_up(http=True, timeout=spawner.http_timeout)
      File "/usr/local/lib/python3.4/dist-packages/jupyterhub/orm.py", line 111, in wait_up
        yield wait_for_http_server(self.url, timeout=timeout)
      File "/usr/local/lib/python3.4/dist-packages/jupyterhub/utils.py", line 82, in wait_for_http_server
        **locals()
    TimeoutError: Server at http://localhost:46693/user/opensuse didn't respond in 30 seconds

=================================

Anything wrong with my installation?
And how could I resolve it?
I try to google and find some way to resolve it, but not sucess

Thanks

Max

**Comment by minrk** [comment]
Try:

    sudo pip3 install notebook

Installing jupyterhub alone will not include everything needed to run the single-user server, since single-user servers may be running on other systems.

**Comment by sakanamax** [comment]
@minrk Thanks, that works !!
Thanks for your kindly help, and jupyter is awesome.

^^

**Comment by raghu20ram** [comment]
@minrk i have already installed notebook using command ```pip install notebook``` is this same as what you said using pip3?
