### ISSUE TITLE
Python 2 kernel produces no output. 

### ISSUE THREAD

**Issue by malgaudreault** [jupyter/jupyterhub#311]
## Python 2 kernel will not run in jupyter

I have several servers running jupyterhub successfully, but it refuses to execute python 2 code on one in particular. This server will run python 3 code just fine, but when a python 2 notebook is open the play button will cause a new cell to appear but will not interpret any of the code.

Jupyter was installed in a virtualenv which was then used to install the python 2 kernel, which is running anaconda. This installation is managed with ansible, so it is the same across all servers. However, the configuration on the server that doesn't run python 2 code is not managed entirely by me as it is used by a different group and they have their own applications running on the server. 

That said, the virtualenv that jupyter is being run under is configured in exactly the same way as it is on the servers that work. The server will open a terminal, activate the anaconda environment, then run code from the ipython console just fine either from jupyter or an ssh session. 

The output from the js console is the same as the output from working servers. The notebook page loads as if everything is fine, the kernel ready message flashes in the upper right corner, and the kernel.js calls happen exactly as they should.

Jupyterhub is being acquired by cloning master to /usr/local/jupyterhub, which is deleted as part of the install process so every new installation gets a clean clone of the jupyterhub repo. At this point the installation has run dozens of times and works just fine on every server we run it on except the one that doesn't interpret python 2 code. 

I have included below the result of commands from a working server and the non working server for comparison. My colleague and I have been at this for a couple of weeks now and we are just about out of ideas any assistance would be appreciated. 

### working
    git log -1
    commit 498c062ee001d5926b601f67648f1993826852c5
    Merge: 0c9214f d1edbdd
    Author: Min RK <benjaminrk@gmail.com>
    Date:   Thu Sep 24 16:09:55 2015 +0200

        Merge pull request #309 from minrk/gen.sleep
    
        use gen.sleep

### broken 
    git log -1
    commit 498c062ee001d5926b601f67648f1993826852c5
    Merge: 0c9214f d1edbdd
    Author: Min RK <benjaminrk@gmail.com>
    Date:   Thu Sep 24 16:09:55 2015 +0200

        Merge pull request #309 from minrk/gen.sleep
    
        use gen.sleep

### working
    [user@system:jupyterhub] source /usr/local/jupyterhub/py/bin/activate

    (py)[user@system:jupyterhub] which python
    /usr/local/jupyterhub/py/bin/python

    (py)[user@system:jupyterhub] python -V
    Python 3.4.3

    (py)[user@system:jupyterhub] which pip
    /usr/local/jupyterhub/py/bin/pip

    (py)[user@system:jupyterhub] pip -V
    pip 7.1.2 from /usr/local/jupyterhub/py/lib/python3.4/site-packages (python 3.4)

    (py)[user@system:jupyterhub] pip list
    coverage (4.0)
    coveralls (1.0)
    decorator (4.0.2)
    docopt (0.6.2)
    ipython (3.2.1)
    ipython-genutils (0.1.0)
    Jinja2 (2.8)
    jsonschema (2.5.1)
    jupyterhub (0.3.0.dev0, /usr/local/jupyterhub)
    MarkupSafe (0.23)
    mistune (0.7.1)
    pamela (0.2.1)
    pip (7.1.2)
    ptyprocess (0.5)
    py (1.4.30)
    Pygments (2.0.2)
    pytest (2.8.0)
    pytest-cov (2.1.0)
    pyzmq (14.7.0)
    requests (2.7.0)
    setuptools (18.2)
    simplepam (0.1.5)
    SQLAlchemy (1.0.8)
    sudospawner (0.0.1, /usr/local/jupyterhub/py/src/sudospawner)
    terminado (0.5)
    tornado (4.2.1)
    traitlets (4.0.0)
    wheel (0.24.0)

### broken 
    [user@broken:jupyterhub] source /usr/local/jupyterhub/py/bin/activate

    (py)[user@broken:jupyterhub] which python
    /usr/local/jupyterhub/py/bin/python

    (py)[user@broken:jupyterhub] python -V
    Python 3.4.3

    (py)[user@broken:jupyterhub] which pip 
    /usr/local/jupyterhub/py/bin/pip

    (py)[user@broken:jupyterhub] pip -V
    pip 7.1.2 from /usr/local/jupyterhub/py/lib/python3.4/site-packages (python 3.4)

    (py)[user@broken:jupyterhub] pip list
    coverage (4.0)
    coveralls (1.0)
    decorator (4.0.2)
    docopt (0.6.2)
    ipython (3.2.1)
    ipython-genutils (0.1.0)
    Jinja2 (2.8)
    jsonschema (2.5.1)
    jupyterhub (0.3.0.dev0, /usr/local/jupyterhub)
    MarkupSafe (0.23)
    mistune (0.7.1)
    pamela (0.2.1)
    pip (7.1.2)
    ptyprocess (0.5)
    py (1.4.30)
    Pygments (2.0.2)
    pytest (2.8.0)
    pytest-cov (2.1.0)
    pyzmq (14.7.0)
    requests (2.7.0)
    setuptools (2.2)
    simplepam (0.1.5)
    SQLAlchemy (1.0.8)
    sudospawner (0.0.1, /usr/local/jupyterhub/py/src/sudospawner)
    terminado (0.5)
    tornado (4.2.1)
    traitlets (4.0.0)
    wheel (0.26.0)

### working 
    [user@system:jupyterhub] source /usr/local/jupyterhub/anaconda/bin/activate ana
    discarding /usr/local/jupyterhub/anaconda/bin from PATH
    prepending /usr/local/jupyterhub/anaconda/envs/ana/bin to PATH

    (ana)[user@system:jupyterhub] which python
    /usr/local/jupyterhub/anaconda/envs/ana/bin/python

    (ana)[user@system:jupyterhub] python -V
    Python 2.7.10 :: Anaconda 2.3.0 (64-bit)

    (ana)[user@system:jupyterhub] which pip
    /usr/local/jupyterhub/anaconda/envs/ana/bin/pip

    (ana)[user@system:jupyterhub] pip -V
    pip 7.0.3 from /usr/local/jupyterhub/anaconda/envs/ana/lib/python2.7/site-packages (python 2.7)

    (ana)[user@system:jupyterhub] pip list
    You are using pip version 7.0.3, however version 7.1.2 is available.
    You should consider upgrading via the 'pip install --upgrade pip' command.
    abstract-rendering (0.5.1)
    alabaster (0.7.3)
    argcomplete (0.8.9)
    astropy (1.0.3)
    Babel (1.3)
    backports.ssl-match-hostname (3.4.0.2)
    bcolz (0.9.0)
    beautifulsoup4 (4.3.2)
    binstar (0.11.0)
    bitarray (0.8.1)
    blaze (0.8.0)
    blz (0.6.2)
    bokeh (0.9.0)
    boto (2.38.0)
    Bottleneck (1.0.0)
    cdecimal (2.3)
    certifi (14.5.14)
    cffi (1.1.0)
    clyent (0.3.4)
    colorama (0.3.3)
    configobj (5.0.6)
    cryptography (0.9.1)
    Cython (0.22.1)
    cytoolz (0.7.3)
    datashape (0.4.5)
    decorator (3.4.2)
    docutils (0.12)
    enum34 (1.0.4)
    fastcache (1.0.2)
    Flask (0.10.1)
    funcsigs (0.4)
    gevent (1.0.1)
    gevent-websocket (0.9.3)
    greenlet (0.4.7)
    grin (1.2.1)
    h5py (2.5.0)
    idna (2.0)
    ipaddress (1.0.7)
    ipykernel (4.0.3)
    ipython (3.2.0)
    ipython-genutils (0.1.0)
    itsdangerous (0.24)
    jdcal (1.0)
    jedi (0.8.1)
    Jinja2 (2.7.3)
    jsonschema (2.4.0)
    jupyter-client (4.0.0)
    jupyter-core (4.0.6)
    llvmlite (0.5.0)
    lxml (3.4.4)
    MarkupSafe (0.23)
    matplotlib (1.4.3)
    mistune (0.5.1)
    mock (1.0.1)
    multipledispatch (0.4.7)
    nbconvert (4.0.0)
    nbformat (4.0.0)
    networkx (1.9.1)
    nltk (3.0.3)
    nose (1.3.7)
    notebook (4.0.5)
    numba (0.19.1)
    numexpr (2.4.3)
    numpy (1.9.2)
    odo (0.3.2)
    openpyxl (1.8.5)
    pandas (0.16.2)
    patsy (0.3.0)
    pep8 (1.6.2)
    Pillow (2.8.2)
    pip (7.0.3)
    ply (3.6)
    psutil (2.2.1)
    ptyprocess (0.4)
    py (1.4.27)
    pyasn1 (0.1.7)
    pycosat (0.6.1)
    pycparser (2.14)
    pycrypto (2.6.1)
    pycurl (7.19.5.1)
    pyflakes (0.9.2)
    Pygments (2.0.2)
    pyOpenSSL (0.15.1)
    pyparsing (2.0.3)
    pytest (2.7.1)
    python-dateutil (2.4.2)
    pytz (2015.4)
    PyYAML (3.11)
    pyzmq (14.7.0)
    redis (2.10.3)
    requests (2.7.0)
    rope (0.9.4)
    runipy (0.1.3)
    scikit-image (0.11.3)
    scikit-learn (0.16.1)
    scipy (0.15.1)
    setuptools (17.1.1)
    six (1.9.0)
    snowballstemmer (1.2.0)
    sockjs-tornado (1.0.1)
    Sphinx (1.3.1)
    sphinx-rtd-theme (0.1.7)
    spyder (2.3.5.2)
    SQLAlchemy (1.0.5)
    statsmodels (0.6.1)
    sympy (0.7.6)
    tables (3.2.0)
    terminado (0.5)
    Theano (0.7.0)
    toolz (0.7.2)
    tornado (4.2)
    traitlets (4.0.0)
    ujson (1.33)
    unicodecsv (0.9.4)
    Werkzeug (0.10.4)
    wheel (0.26.0)
    xlrd (0.9.3)
    XlsxWriter (0.7.3)
    xlwt (1.0.0)

    (ana)[user@system:jupyterhub] ipython -V
    3.2.0

### broken
    [user@broken:jupyterhub] source /usr/local/jupyterhub/anaconda/bin/activate ana
    discarding /usr/local/jupyterhub/anaconda/bin from PATH
    prepending /usr/local/jupyterhub/anaconda/envs/ana/bin to PATH

    (ana)[user@broken:jupyterhub] which python
    /usr/local/jupyterhub/anaconda/envs/ana/bin/python

    (ana)[user@broken:jupyterhub] python -V
    Python 2.7.10 :: Anaconda 2.3.0 (64-bit)

    (ana)[user@broken:jupyterhub] which pip
    /usr/local/jupyterhub/anaconda/envs/ana/bin/pip

    (ana)[user@broken:jupyterhub] pip -V
    pip 7.0.3 from /usr/local/jupyterhub/anaconda/envs/ana/lib/python2.7/site-packages (python 2.7)

    (ana)[user@broken:jupyterhub] pip list
    You are using pip version 7.0.3, however version 7.1.2 is available.
    You should consider upgrading via the 'pip install --upgrade pip' command.
    abstract-rendering (0.5.1)
    alabaster (0.7.3)
    argcomplete (0.8.9)
    astropy (1.0.3)
    Babel (1.3)
    backports.ssl-match-hostname (3.4.0.2)
    bcolz (0.9.0)
    beautifulsoup4 (4.3.2)
    binstar (0.11.0)
    bitarray (0.8.1)
    blaze (0.8.0)
    blz (0.6.2)
    bokeh (0.9.0)
    boto (2.38.0)
    Bottleneck (1.0.0)
    cdecimal (2.3)
    certifi (14.5.14)
    cffi (1.1.0)
    clyent (0.3.4)
    colorama (0.3.3)
    configobj (5.0.6)
    cryptography (0.9.1)
    Cython (0.22.1)
    cytoolz (0.7.3)
    datashape (0.4.5)
    decorator (3.4.2)
    docutils (0.12)
    enum34 (1.0.4)
    fastcache (1.0.2)
    Flask (0.10.1)
    funcsigs (0.4)
    gevent (1.0.1)
    gevent-websocket (0.9.3)
    greenlet (0.4.7)
    grin (1.2.1)
    h5py (2.5.0)
    idna (2.0)
    ipaddress (1.0.7)
    ipykernel (4.0.3)
    ipython (3.2.0)
    ipython-genutils (0.1.0)
    itsdangerous (0.24)
    jdcal (1.0)
    jedi (0.8.1)
    Jinja2 (2.7.3)
    jsonschema (2.4.0)
    jupyter-client (4.0.0)
    jupyter-core (4.0.6)
    llvmlite (0.5.0)
    lxml (3.4.4)
    MarkupSafe (0.23)
    matplotlib (1.4.3)
    mistune (0.5.1)
    mock (1.0.1)
    multipledispatch (0.4.7)
    nbconvert (4.0.0)
    nbformat (4.0.0)
    networkx (1.9.1)
    nltk (3.0.3)
    nose (1.3.7)
    notebook (4.0.5)
    numba (0.19.1)
    numexpr (2.4.3)
    numpy (1.9.2)
    odo (0.3.2)
    openpyxl (1.8.5)
    pandas (0.16.2)
    patsy (0.3.0)
    pep8 (1.6.2)
    Pillow (2.8.2)
    pip (7.0.3)
    ply (3.6)
    psutil (2.2.1)
    ptyprocess (0.4)
    py (1.4.27)
    pyasn1 (0.1.7)
    pycosat (0.6.1)
    pycparser (2.14)
    pycrypto (2.6.1)
    pycurl (7.19.5.1)
    pyflakes (0.9.2)
    Pygments (2.0.2)
    pyOpenSSL (0.15.1)
    pyparsing (2.0.3)
    pytest (2.7.1)
    python-dateutil (2.4.2)
    pytz (2015.4)
    PyYAML (3.11)
    pyzmq (14.7.0)
    redis (2.10.3)
    requests (2.7.0)
    rope (0.9.4)
    runipy (0.1.3)
    scikit-image (0.11.3)
    scikit-learn (0.16.1)
    scipy (0.15.1)
    setuptools (17.1.1)
    six (1.9.0)
    snowballstemmer (1.2.0)
    sockjs-tornado (1.0.1)
    Sphinx (1.3.1)
    sphinx-rtd-theme (0.1.7)
    spyder (2.3.5.2)
    SQLAlchemy (1.0.5)
    statsmodels (0.6.1)
    sympy (0.7.6)
    tables (3.2.0)
    terminado (0.5)
    Theano (0.7.0)
    toolz (0.7.2)
    tornado (4.2)
    traitlets (4.0.0)
    ujson (1.33)
    unicodecsv (0.9.4)
    Werkzeug (0.10.4)
    wheel (0.26.0)
    xlrd (0.9.3)
    XlsxWriter (0.7.3)
    xlwt (1.0.0)

    (ana)[user@broken:jupyterhub] ipython -V
    3.2.0

### working
    [user@system:jupyterhub] cat /usr/local/share/jupyter/kernels/python2/kernel.json
    {
     "display_name": "Python 2",
     "language": "python",
     "argv": [
      "/usr/local/jupyterhub/anaconda/envs/ana/bin/python",
      "-m",
      "IPython.kernel",
      "-f",
      "{connection_file}"
     ]
    }

    [user@system:jupyterhub] cat /usr/local/share/jupyter/kernels/python3/kernel.json
    {
     "language": "python",
     "argv": [
      "/usr/local/jupyterhub/py/bin/python3.4",
      "-m",
      "IPython.kernel",
      "-f",
      "{connection_file}"
     ],
     "display_name": "Python 3"
    }

### broken
    [user@broken:jupyterhub] cat /usr/local/share/jupyter/kernels/python2/kernel.json
    {
     "display_name": "Python 2",
     "language": "python",
     "argv": [
      "/usr/local/jupyterhub/anaconda/envs/ana/bin/python",
      "-m",
      "IPython.kernel",
      "-f",
      "{connection_file}"
     ]
    }

    [user@broken:jupyterhub] cat /usr/local/share/jupyter/kernels/python3/kernel.json
    {
     "argv": [
      "/usr/local/jupyterhub/py/bin/python",
      "-m",
      "IPython.kernel",
      "-f",
      "{connection_file}"
     ],
     "language": "python",
     "display_name": "Python 3"
    }

That's everything I can think of at the moment. Please let me know if there's additional information that would be helpful.

**Comment by minrk** [comment]
What happens if you try to start the Python 2 kernel manually:

    /usr/local/jupyterhub/anaconda/envs/ana/bin/python -m IPython.kernel --debug

**Comment by malgaudreault** [comment]
/usr/local/jupyterhub/anaconda/envs/ana/bin/python -m IPython.kernel --debug
    [IPKernelApp] Config changed:
    [IPKernelApp] {'IPKernelApp': {'log_level': 10}}
    [IPKernelApp] IPYTHONDIR set to: /root/.ipython
    [IPKernelApp] Using existing profile dir: u'/root/.ipython/profile_default'
    [IPKernelApp] Searching path [u'/root', u'/root/.ipython/profile_default', '/usr/local/etc/ipython', '/etc/ipython'] for config files
    [IPKernelApp] Attempting to load config file: ipython_config.py
    [IPKernelApp] Loaded config file: /etc/ipython/ipython_config.py
    [IPKernelApp] Config changed:
    [IPKernelApp] {'LocalEngineLauncher': {'engine_cmd': ['/usr/bin/python2', '-m', 'IPython.parallel.engine']}, 'LocalControllerLauncher': {'controller_cmd': ['/usr/bin/python2', '-m', 'IPython.parallel.controller']}, 'IPKernelApp': {'log_level': 10}, 'LocalEngineSetLauncher': {'engine_cmd': ['/usr/bin/python2', '-m', 'IPython.parallel.engine']}}
    [IPKernelApp] Attempting to load config file: ipython_kernel_config.py
    [IPKernelApp] Connection file not found: kernel-10913.json
    [IPKernelApp] Starting the kernel at pid: 10913
    [IPKernelApp] shell ROUTER Channel on port: 40448
    [IPKernelApp] iopub PUB Channel on port: 40808
    [IPKernelApp] stdin ROUTER Channel on port: 55122
    [IPKernelApp] control ROUTER Channel on port: 59589
    [IPKernelApp] Heartbeat REP Channel on port: 48149
    [IPKernelApp] To connect another client to this kernel, use:
    [IPKernelApp]     --existing kernel-10913.json
    NOTE: When using the `ipython kernel` entry point, Ctrl-C will not work.

    To exit, you will have to explicitly quit this process, by either sending
    "quit" from a client, or using Ctrl-\ in UNIX-like environments.

    To read more about this, see https://github.com/ipython/ipython/issues/2049


    To connect another client to this kernel, use:
       --existing kernel-10913.json
    [IPKernelApp] Writing connection file: /root/.ipython/profile_default/security/kernel-10913.json
    [IPKernelApp] Loading IPython extensions...
    [IPKernelApp] Loading IPython extension: storemagic

**Comment by minrk** [comment]
Can you include the JupyterHub config on the bad machine? Is it possible to run *without* the sudo spawner for testing? That's one that's quite difficult to debug.

**Comment by malgaudreault** [comment]
The problem existed with or without the sudo spawner enabled. The config was default, so there would be no config to post as you can get the config we were using with generate_config. 

We ended up just rebuilding the machine since it looks like it was some idiosyncrasy of that particular machine's configuration. I think this issue can be safely closed.

Thanks a ton for your help with this, I really appreciate your time.
