### ISSUE TITLE
configurable-http-proxy running out of file descriptors

### ISSUE THREAD

**Issue by cgsanchez** [jupyter/jupyterhub#312]
Ran today into a wall, kinda, with configurable-http-proxy eating out all file descriptors. My setup is similar to that used in https://github.com/compmodels . We are using dockerspawner with the systemuser container runing on a swarm cluster. The main jupyterhub process runs non containerized in a dedicated server, that handles the swarm manager. This allows us to scale elastically if necesary. We went into production mode today and after 20 or so users where logged in, the proxy started spitting out blood:

error: [ConfigProxy] Proxy error: code=EMFILE, errno=EMFILE, syscall=connect

Increasing the file descriptor limit (ulimit -n) eventually solved the problem (thanx @minrk  for the tip, saved my day!). However, with five more days of workshop to go I would like to understand the nature of the problem.  It seems unreasonable to me, and this is pure ignorance of the inner workings, that proxying to 40 containers in the back requires configurable-http-proxy of the order of 1000 descriptors. Is this a feature? Is there something one can tweak to make this more predictable?

**Comment by jhamrick** [comment]
Huh, interesting. I'm running JupyterHub+config-http-proxy in a Docker container and never ran into this issue, but I know that @minrk and @rgbkrk had trouble with running out of file descriptors on tmpnb. We tried to replicate the issue with file descriptors on compmodels, but never could -- maybe the reason is because it works ok *within* Docker, but not when you run it outside of a container?

**Comment by rgbkrk** [comment]
The ulimits within Docker are cranked up pretty high by default, for a normal system you'll have to set them accordingly. The reason this occurs is a property of websockets - the fact that every connection is going to take up a port between the proxy and the notebook server, continuously.

**Comment by cgsanchez** [comment]
Thanx guys, now setting up ulimits -n 10^16 from /etc/security/limits.conf. Closing this.
