### ISSUE TITLE
No such file or directory: 'jupyterhub-singleuser'

### ISSUE THREAD

**Issue by dbuendiab** [jupyter/jupyterhub#313]
I'm stuck in the login step. I receive Error 500 when trying to log . The error message is *No such file or directory: 'jupyterhub-singleuser'*. But I have those files, **jupyterhub** and **jupyterhub-singleuser**, in my ~/myproject/bin folder.

What can be the reason? Reading the trace, it seems something fails when trying to spawn the new process. I've tried the configuration proposed in https://github.com/jupyter/jupyterhub/blob/master/docs/getting-started.md#example
(just without the SSL part) and yet I'm receiving the same error (500 in web page, No such file in console)

[ec2-user@ip-172-30-0-11 bin]$ sudo ./jupyterhub
[I 2015-09-29 08:19:04.530 JupyterHub app:532] Writing cookie_secret to /home/ec2-user/myproject/bin/jupyterhub_cookie_secret
[W 2015-09-29 08:19:04.617 JupyterHub app:257]
    Generating CONFIGPROXY_AUTH_TOKEN. Restarting the Hub will require restarting the proxy.
    Set CONFIGPROXY_AUTH_TOKEN env or JupyterHub.proxy_auth_token config to avoid this message.

[W 2015-09-29 08:19:04.630 JupyterHub app:631] No admin users, admin interface will be unavailable.
[W 2015-09-29 08:19:04.630 JupyterHub app:632] Add any administrative users to `c.Authenticator.admin_users` in config.
[I 2015-09-29 08:19:04.631 JupyterHub app:652] Not using whitelist. Any authenticated user will be allowed.
[I 2015-09-29 08:19:04.640 JupyterHub app:1031] Hub API listening on http://localhost:8081/hub/
[I 2015-09-29 08:19:04.643 JupyterHub app:788] Starting proxy @ http://*:8000/
08:19:04.760 - info: [ConfigProxy] Proxying http://*:8000 to http://localhost:8081
08:19:04.764 - info: [ConfigProxy] Proxy API at http://localhost:8001/api/routes
[I 2015-09-29 08:19:04.848 JupyterHub app:1054] JupyterHub is now running at http://localhost:8000/
[I 2015-09-29 08:19:12.456 JupyterHub log:100] 302 GET / (@47.62.216.109) 1.34ms
[I 2015-09-29 08:19:12.498 JupyterHub log:100] 302 GET / (@47.62.216.109) 0.73ms
[I 2015-09-29 08:19:12.569 JupyterHub log:100] 302 GET /hub (@47.62.216.109) 0.86ms
[I 2015-09-29 08:19:12.644 JupyterHub log:100] 302 GET /hub/ (@47.62.216.109) 0.87ms
[I 2015-09-29 08:19:22.828 JupyterHub spawner:363] Spawning jupyterhub-singleuser --user=jupyter --port=56158 --cookie-name=jupyter-hub-token-jupyter --base-url=/user/jupyter --hub-prefix=/hub/ --hub-api-url=http://localhost:8081/hub/api --ip=localhost
[E 2015-09-29 08:19:22.831 JupyterHub orm:379] Unhandled error starting jupyter's server: [Errno 2] No such file or directory: 'jupyterhub-singleuser'
[E 2015-09-29 08:19:22.839 JupyterHub web:1496] Uncaught exception POST /hub/login?next= (47.62.216.109)
    HTTPServerRequest(protocol='http', host='52.19.127.35:8000', method='POST', uri='/hub/login?next=', version='HTTP/1.1', remote_ip='47.62.216.109', headers={'Content-Length': '36', 'Accept-Language': 'es,en-US;q=0.8,en;q=0.6,ca;q=0.4', 'X-Forwarded-Proto': 'http', 'Upgrade-Insecure-Requests': '1', 'Origin': 'http://52.19.127.35:8000', 'Content-Type': 'application/x-www-form-urlencoded', 'X-Forwarded-For': '47.62.216.109', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.99 Safari/537.36', 'Host': '52.19.127.35:8000', 'X-Forwarded-Port': '8000', 'Accept-Encoding': 'gzip, deflate', 'Referer': 'http://52.19.127.35:8000/hub/login', 'Connection': 'close', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8', 'Cache-Control': 'max-age=0'})
    Traceback (most recent call last):
      File "/home/ec2-user/myproject/local/lib64/python3.4/site-packages/tornado/web.py", line 1415, in _execute
        result = yield result
      File "/home/ec2-user/jupyterhub/jupyterhub/handlers/login.py", line 73, in post
        yield self.spawn_single_user(user)
      File "/home/ec2-user/jupyterhub/jupyterhub/handlers/base.py", line 286, in spawn_single_user
        yield gen.with_timeout(timedelta(seconds=self.slow_spawn_timeout), f)
      File "/home/ec2-user/jupyterhub/jupyterhub/orm.py", line 389, in spawn
        raise e
      File "/home/ec2-user/jupyterhub/jupyterhub/orm.py", line 370, in spawn
        yield gen.with_timeout(timedelta(seconds=spawner.start_timeout), f)
      File "/home/ec2-user/jupyterhub/jupyterhub/spawner.py", line 365, in start
        preexec_fn=self.make_preexec_fn(self.user.name),
      File "/usr/lib64/python3.4/subprocess.py", line 859, in __init__
        restore_signals, start_new_session)
      File "/usr/lib64/python3.4/subprocess.py", line 1457, in _execute_child
        raise child_exception_type(errno_num, err_msg)
    FileNotFoundError: [Errno 2] No such file or directory: 'jupyterhub-singleuser'

**Comment by minrk** [comment]
what is `$PATH`?

**Comment by dbuendiab** [comment]
Excuse me for being late, but I've tryed again from the scratch, as I wanted to reproduce the issue again.

My scenario is as follows:
* I'm using AWS.
* I want to set an AMI with JupyterHub preinstalled.
* I'm trying to be simple, because I try to avoid Linux intricacies.

The help I get in [README.md](https://github.com/jupyter/jupyterhub) is a little confusing for me, I am an experienced programmer (near 40 years in business!) but I'm nearly a newbie in Linux and Open Source (but I like it a lot). 

Despite of my good intentions, I've had to struggle a lot with Linux flavours issues. The basic machine Amazon Linux is RedHat/CentOS based, so you install packages with **yum** and not **apt-get**. Frequently what someone suggests is inappropiate for the Linux you're dealing with.

Also, there are issues with Python versions, as the installed one is Python 2.7 by default and JupyterHub is said to work with Python 3, if I'm not wrong (but in recent deployments there is a good solution via *alternatives* that avoids the need for *virtualenv*).

Another problem I've faced is related to the Key Pair authentication. AWS only is accesible with an user **ec2-user**, and with no password. After doing a lot of frustrating installations, the usr/pwd  login for JupyterHub always failed. But this is an AWS based issue.

Finally, I've set a machine with an user **jupyter** with password, and got it into the **wheel** group to make it sudoer. I've done all the installation process with this user, and then it's worked, at last.

I write here the "recipe", for if you think it can help to complement the installation info. I don't know well how to help with documentation in GitHub, but I think the info itself is valuable (at least for the week I've spent digging in).

Here it goes:

* I suppose we have a brand new virtual server created on AWS. The server is configured with defaults, we'll only need to set the **Security Groups" to handle SSH and TCP on port 8000. Also we'll need a .pem file with the Key Pair for authentication. The two things are easy to manage in AWS Console EC2 Dashboard.

* First SSH to the server (you have its public IP in EC2 Dashboard):
ssh -i pemfile.pem ec2-user@ip.ip.ip.ip

* Then execute the next commands: 
```javascript
// Update the server with last minute packages
sudo yum update
// Install python3.4
sudo yum install python34-virtualenv
// Set python3.4 as default (instead of using virtualenv)
sudo alternatives --set python /usr/bin/python3.4
// Enable EPEL repository (for nodejs)
sudo yum-config-manager --enable epel
// Install NodeJS
sudo yum install nodejs npm
// Install proxy
sudo npm install -g configurable-http-proxy
// Create new user (jupyter) in wheel group
sudo adduser --gid wheel jupyter
// Set the password
sudo passwd jupyter		

// Edit sudoers file giving sudo without password privilege to wheel group
sudo nano /etc/sudoers
    %wheel  ALL=(ALL)       NOPASSWD: ALL

// Enable SSH with password access editintg sshd_config
sudo nano /etc/ssh/sshd_config
    PasswordAuthentication yes

// Restart SSH to reconfigure
sudo service sshd restart

// exit SSH
exit

// SSH 
ssh jupyter@ip.ip.ip.ip
```

* This is a good place to take a snapshot of the server, just to not to do everything again from the beginning if we are wrong from now on.

* Then continue:
```javascript
// Install iPython with notebook dependencies
sudo pip install "ipython[notebook]"

// Install JupyterHub
sudo pip install jupyterhub

// Start the application
jupyterhub
```

Lucky enough, you can login using jupyter usr/pwd credentials. 

After arriving here, I'll give a try to the multiuser question. I hope it easier. But it's enough, by now.

Thank you, and excuse me for the long post. I had to let off steam, I suppose.

**Comment by alfonsonishikawa** [comment]
I fixed it configuring the following in jupyterhub_config.py:

`c.Spawner.cmd = ['fullpath-to/jupyterhub-singleuser']`

(maybe I have a later Jupyterhub version?)

**Comment by yash64** [comment]
@minrk  I am having the same issue. In jupyterhub web i get below error message
```
500 : Internal Server Error
Error in Authenticator.pre_spawn_start: FileNotFoundError [Errno 2] No such file or directory: 'jupyterhub-singleuser': 'jupyterhub-singleuser'
```

In the terminal I see below

```
   Traceback (most recent call last):
      File "/home/yaswanth/anaconda3/lib/python3.7/site-packages/jupyterhub/app.py", line 2716, in launch_instance_async
        await self.start()
      File "/home/yaswanth/anaconda3/lib/python3.7/site-packages/jupyterhub/app.py", line 2524, in start
        await self.proxy.get_all_routes()
      File "/home/yaswanth/anaconda3/lib/python3.7/site-packages/jupyterhub/proxy.py", line 806, in get_all_routes
        resp = await self.api_request('', client=client)
      File "/home/yaswanth/anaconda3/lib/python3.7/site-packages/jupyterhub/proxy.py", line 774, in api_request
        result = await client.fetch(req)
    tornado.httpclient.HTTPClientError: HTTP 403: Forbidden
```

I am starting jupyterhub with `sudo /home/yaswanth/anaconda3/bin/jupyterhub`. I have tried with all possible ways mentioned in other issues as well. I have included my `$PATH` below

```
/home/yaswanth/.local/bin:/home/yaswanth/anaconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/Program Files/WindowsApps/CanonicalGroupLimited.Ubuntu18.04onWindows_1804.2020.423.0_x64__79rhkp1fndgsc:/mnt/c/Windows/system32:/mnt/c/Windows:/mnt/c/Windows/System32/Wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0:/mnt/c/Windows/System32/OpenSSH:/mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/mnt/c/Program Files/NVIDIA Corporation/NVIDIA NvDLISR:/mnt/c/Program Files/Java/jdk-11.0.5/bin:/mnt/c/Program Files/Apache-Maven/apache-maven-3.6.3/bin:/mnt/c/Users/yaswa/AppData/Local/Programs/Python/Python38/Scripts:/mnt/c/Users/yaswa/AppData/Local/Programs/Python/Python38:/mnt/c/Users/yaswa/AppData/Local/Microsoft/WindowsApps:/snap/bin:/home/yaswanth/anaconda3/bin:/home/yaswanth/anaconda3/etc/jupyterhub
```
I have also given the absolute path  `c.Spawner.cmd = ['/home/yaswanth/anaconda3/bin/jupyterhub-singleuser']` in `jupyterhub_config.py` file but still I get the same issue.

Can you please help me with this.

**Comment by yash64** [comment]
@minrk @willingc can you please help me with this issue updated above.

**Comment by manics** [comment]
@yash64 Please open a support thread on the Jupyter Community Forum: https://discourse.jupyter.org/ with full details of your setup.

**Comment by yash64** [comment]
> @yash64 Please open a support thread on the Jupyter Community Forum: https://discourse.jupyter.org/ with full details of your setup.

Thanks @manics. I have opened the thread in discourse yesterday. Hoping someone to help me.

**Comment by ttklm20** [comment]
# Run "which jupyterhub-singleuser", get your real path to  jupyterhub-singleuser, 
# Then，create a symlink for jupyterhub-singleuser from the real path to "/usr/local/bin/", like : 

ln -s /usr/local/python3.6/bin/jupyterhub-singleuser /usr/local/bin/jupyterhub-singleuser
