### ISSUE TITLE
setting spawned jupyterhub working directory outside of the home directory

### ISSUE THREAD

**Issue by mogthesprog** [jupyter/jupyterhub#314]
Okay so this may be a non issue but i can't seem to get it working.

Using the c.Spawner.notebook_dir = '', I want to spawn a notebook with the workdir of:

"/path/to/file/username"

that is, I want to not use the home directories but something outside that. I've tried using the "getpass" module to get the username and then appending it to the config line in the jupyterhub_config.py file with something like,

import getpass
a = getpass.getuser()
c.Spawner.notebook_dir = '/path/to/dir/' + a

but it doesn't seem to work. any ideas how i can solve this?

Cheers,

Morgan

**Comment by jhamrick** [comment]
The `jupyterhub_config.py` file is loaded by the user that you run JupyterHub with, so the way you're trying to do it won't work.

It's possible that this would actually require modifying the behavior of the spawner (so that you could maybe pass in a format string that will get formatted with the appropriate user id?) but perhaps there is a better way to do it. @minrk do you know?

**Comment by minrk** [comment]
I don't think this is possible with pure config right now. You would have to subclass Spawner, which you can do in a config file, for small changes like this:

```python
from jupyterhub.spawner import Spawner

class MySpawner(Spawner):
    def _notebook_dir_default(self):
        return '/path/to/dir/' + self.user.name

c.JupyterHub.spawner_class = MySpawner
```

**Comment by mogthesprog** [comment]
Hey guys, Cheers for the quick reply, really appreciate it.

So I've put that info into my config file and i get "500 internal server error". Any ideas? I've put the above into my config file and amended the directory. Then I executed jupyterhub with the -f flag and the path to the config file.

**Comment by jld23** [comment]
I was working on the same feature today. When I try @minrk suggestion I get the following:
[I 2015-09-29 15:59:03.821 JupyterHub app:652] Not using whitelist. Any authenticated user will be allowed.
[D 2015-09-29 15:59:03.824 JupyterHub app:709] Loading state for jadean from db
[E 2015-09-29 15:59:03.824 JupyterHub app:1096]
    Traceback (most recent call last):
      File "/python3/dev/jupyterhub/jupyterhub/app.py", line 1093, in launch_instance_async
        yield self.initialize(argv)
      File "/python3/dev/jupyterhub/jupyterhub/app.py", line 912, in initialize
        yield self.init_spawners()
      File "/python3/dev/jupyterhub/jupyterhub/app.py", line 714, in init_spawners
        status = yield spawner.poll()
      File "/python3/dev/jupyterhub/jupyterhub/spawner.py", line 189, in poll
        raise NotImplementedError("Override in subclass. Must be a Tornado gen.coroutine.")
    NotImplementedError: Override in subclass. Must be a Tornado gen.coroutine.

[D 2015-09-29 15:59:03.825 JupyterHub application:581] Exiting application: jupyterhub
v64-d7b445-02>

**Comment by mogthesprog** [comment]
can you show me your config.py please?

**Comment by minrk** [comment]
Sorry, subclassed the incomplete baseclass instead of the real one. Fixed to `LocalProcessSpawner` above.

**Comment by jld23** [comment]
Thanks @minrk ! Worked perfectly
Here is the full code. Make user you have an ending '/' on the directory
`from jupyterhub.spawner import LocalProcessSpawner

class MySpawner(LocalProcessSpawner):
    def _notebook_dir_default(self):
        return '/python3/notebooks/' + self.user.name

c.JupyterHub.spawner_class = MySpawner'

**Comment by mogthesprog** [comment]
Sorry @minrk, been manic this last week.

Worked perfectly! I'll close this now.

Cheers,

Morgan

**Comment by ramnavan** [comment]
@minrk - Thank You! Can we use this same mechanism to point to S3 bucket or GitHub repo?

**Comment by minrk** [comment]
@ramnavan this is only for directories. So the answer is yes, if you mount S3 with s3fs, or clone the github repo to the filesystem.

**Comment by ubertao** [comment]
I recently ran into this issue. What I did is to put the following in jupyter server config:

```python
import os
username = os.environ['USER']
c.ServerApp.preferred_dir = f'/var/jupyter/notebooks/{username}'
```
