### ISSUE TITLE
Question about loading nbextensions

### ISSUE THREAD

**Issue by parmentelat** [jupyter/jupyterhub#315]
Hi there

I've found here
https://carreau.gitbooks.io/jupyter-book/content/notebook-extensions.html
a nice article on notebook extensions, which turned out very useful

I understand this might be a work in progress, but I was curious to better understand the point of this

    IPython.notebook.config.update({
      "load_extensions": {"hello-scipy":true}
    })

What exactly is the impact of that ? Does it have an effect that goes beyond the current browser ? 

I am under the impression that in my case it became rather persistent for that user, to the point that I was not able to remove this extension from the set of autoloaded ones once I was ok with my own.

I guess it would be helpful to also give the sentence that undoes this. 

And many thanks for the great tool, this is awesome :)

**Comment by minrk** [comment]
> What exactly is the impact of that?

It updates the configuration of the notebook to load the `hello-scipy` extension on startup. This configuration is associated with the notebook *server*, so it is independent of your browser.

You can run this code to revert the configuration:

```javascript
IPython.notebook.config.update({
  "load_extensions": {"hello-scipy":null}
})
```

after which point hello-scipy will not be loaded anymore.
