### ISSUE TITLE
Bad config encountered during initialization. The 'parent' trait of a FileContentsManager instance must be a Configurable

### ISSUE THREAD

**Issue by robdempsey** [jupyter/jupyterhub#322]
Hi

My setup

Python 3.4.3 |Continuum Analytics, Inc.| (default, Jun  4 2015, 15:29:08)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux

jupyterhub        - JupyterHub: A multi-user server for Jupyter notebooks
INSTALLED: 0.2.0 (latest)

When I try and get a notebook running I get the following error

[D 2015-10-14 11:10:38.557 JupyterHub spawner:221] Polling subprocess every 30s
/opt/miniconda3/miniconda3/lib/python3.4/site-packages/IPython/utils/traitlets.py:5: UserWarning: IPython.utils.traitlets has moved to a top-level traitlets package.
  warn("IPython.utils.traitlets has moved to a top-level traitlets package.")
/opt/miniconda3/miniconda3/lib/python3.4/site-packages/IPython/kernel/__init__.py:13: ShimWarning: The `IPython.kernel` package has been deprecated. You should import from ipykernel or jupyter_client instead.
  "You should import from ipykernel or jupyter_client instead.", ShimWarning)
/opt/miniconda3/miniconda3/lib/python3.4/site-packages/IPython/utils/log.py:5: UserWarning: IPython.utils.log has moved to traitlets.log
  warn("IPython.utils.log has moved to traitlets.log")
[C 2015-10-14 11:10:39.244 jupyterhub application:78] Bad config encountered during initialization:
[C 2015-10-14 11:10:39.244 jupyterhub application:79] The 'parent' trait of a FileContentsManager instance must be a Configurable, but a value of class '__main__.SingleUserNotebookApp' (i.e. <__main__.SingleUserNotebookApp object at 0x7fc2e6db7518>) was specified.

Any Ideas?

Thanks

Rob

**Comment by minrk** [comment]
I think this is fixed in master. I'll try to cut a new release before too long, but installing from git should work.

**Comment by robdempsey** [comment]
Hi

Good news.  Do you know when it could be released? - I have issues with access to github on some servers.

Thanks

Rob

**Comment by minrk** [comment]
In the next week, probably.
