### ISSUE TITLE
Jupyterhub not sourcing env variables in python kernel

### ISSUE THREAD

**Issue by kehey** [jupyter/jupyterhub#330]
We have recently installed jupyterhub, but have one annoying problem left: in the python kernel, our environment variables are not sourced.

The problem is specific for the python kernel in jupyterhub, as performing os.environ in a local jupyter notebook (just launching one in command line) or qtconsole gives all our environment variables. On the other hand, the R and bash kernel do have the env variables loaded in the jupyterhub as well.

So at this point, we're not quite sure where the problem would locate: in the kernel (but working for a qtconsole) or in the jupyterhub (but working for bash and R kernel). using the ! or %%bash in the python kernel also does not have the env variables loaded.

Any idea where the difference would lie between the command line notebook and the hub initialisation of the python kernel? And why this is not affecting the R or bash kernel?

**Comment by minrk** [comment]
How are you defining the variables?

**Comment by kehey** [comment]
They are sourced from a number of files upon login in a shell.

**Comment by minrk** [comment]
That would probably be it, then. JupyterHub doesn't instantiate a shell for the user. It makes sense that bash would get this, since presumably these are bash startup files. I'm a bit surprised that R would initialize a shell before starting itself, though.

Are these environment variables different for each user, or system-wide? JupyterHub uses a whitelist of environment variables called `env_keep` to pass from the Hub process down to the user processes, to avoid leaking credentials and things.

**Comment by kehey** [comment]
And the command line jupyter notebook will just run as a process in the shell compared to the one running in the hub environment then...

The env variables are system-wide. I read about the env_keep, but I was sort of hoping not needing to list them all. I will check, but would the jupytherhub process have access to the env variables? Because then I can probably just append the os.environ list to the env_keep list programmatically and set that list as env_keep with

```
c.Spawner.env_keep.append('JUPYTER_DATA_DIR')
```

**Comment by minrk** [comment]
If you started the Hub in a shell, it will have all of those env variables. If you use something like supervisor, it may not. You can certainly programmatically populate env_keep in `jupyterhub_config.py`, and give yourself an effective blacklist instead of the whitelist currently used.

**Comment by kehey** [comment]
This worked, thanks!!

**Comment by jingkungao** [comment]
@kehey I have the same issue. Can you kindly point to me how to add the path, e.g.,
LD_LIBRARY_PATH=/usr/local/cuda/lib
to the env?
I tried c.Spawner.env_keep.append(['LD_LIBRARY_PATH']), which doesn't work.

Thanks!

**Comment by kehey** [comment]
Hi,

what I did was the following piece of code:

```python
import os
for var in os.environ:
    c.Spawner.env_keep.append(var)
```
This allows to add a sinlge if statement later on to filter the vars that may not be kept. But using this piece, you should have access to all env vars.

**Comment by jingkungao** [comment]
Thanks!
This is helpful! It's same as c.Spawner.env_keep.append('LD_LIBRARY_PATH').
However, it doesn't seem to work in my case. When I type
!env
in the notebook started from jupyterhub, I am still not able to see

LD_LIBRARY_PATH=/usr/local/cuda-7.0/lib64:

The weird thing is that this only happens to jupyterhub, if I tried ipython
notebook, all the environment variables are loaded correctly.

Not sure if there are other tricks I should use to make it work.

**Comment by kehey** [comment]
yes, it is only in the hub. Given the comment of minrk before: is jupyterhub launched from a shell? Because if not, your launching environment might also not have your library path, in which case there is nothing to keep. You can also in your config just add ```print(os.environ)``` and then you'll see in the log what env variables your jupyterhub process has access to. If it's not in that list, then you also can't pass it through.

You might also want to check whether there are no typo's anywhere in the config. They can cause the config to be silently ignored I noticed. You could start by generating a clean config and only adapting that piece.

**Comment by jingkungao** [comment]
Thanks for giving me these pointers! It worked our eventually!

I started jupyterhub in my account using "sudo jupyterhub -f
./jupyterhub_config.py" where I was using zsh. I guesses although I
configured .zshrc/.bashrc to include the environment variables, "sudo" kind
of ignored it. So I went to root account and configured .bashrc in root,
then start jupyterhub from root directly by running "jupyterhub -f
./jupyterhub_config.py".

Not exactly sure why jupyterhub won't be able to read environment variables
in my account, but I am glad there is a work-around to solve this by going
to root account.

Thanks again!

**Comment by wtbarnes** [comment]
I don't know if this is still relevant to anyone, but it appears that exporting LD_LIBRARY_PATH is a bit of a 'gotcha.' It seems that the OS will remove environment variables related to dynamic linking. See [here](http://serverfault.com/questions/371630/how-to-configure-sudoers-to-always-keep-ld-library-path-envrionment-variable) for more details. 

Otherwise, setting
```Python
c.Spawner.env_keep.append('MY_ENV_VAR')
``` 
in `/etc/jupyterhub/jupyterhub_config.py` and 
```Shell
Defaults    env_keep += "MY_ENV_VAR"
```
in `/etc/sudoers` seems to do the trick as noted by many others above.

**Comment by kirk86** [comment]
@kehey where does `c` comes from at `c.Spawner...` ?

**Comment by minrk** [comment]
It's injected by the config system.

**Comment by itsindra** [comment]
Any way in which we can have every user's bashrc loaded for their single user instances? (I know its not the safest thing to do, but if this is a "safe" env)

**Comment by DataVictorEngineer** [comment]
Hi all, 

  I was trying to configure the jupyterhub_config.py, but it didn't work for me, I am starting the jupyterhub service as: systemctl start jupyterhub.

My solution was to set the environment variable in the jupyter_notebook_config.py:

`import os
os.environ['DSP_CONFIGS'] = '/src/ds_datamanagement_scripts/'`

Hope it helps !

**Comment by minrk** [comment]
> Any way in which we can have every user's bashrc loaded for their single user instances?

Yes! If you change `c.Spawner.cmd` to a custom entrypoint, it can source whatever you like. For instance, this example uses `bash -l` to invoke a login shell (sources everything you get in a normal interactive session):

```bash
#!/usr/bin/env bash -l

# additional things you want that might not be in the default shell:
export SOME_EXTRA_ENV=x

# it should always end with this line, to start the notebook server:
exec jupyterhub-singleuser "$@"
```

Then set:

```python
c.Spawner.cmd = '/path/to/my-launch-singleuser`
```

LocalProcessSpawner has a shortcut for this:

```python
c.Spawner.shell_cmd = ['bash', '-l', '-c']
```


You can also try to do this in one line without the extra layer of indirection, but I'm not sure it's 100% reliable:

```python
c.Spawner.cmd = ['bash', '-l', '-c', 'exec jupyterhub-singleuser "$@"', '--']
```

**Comment by marius311** [comment]
If I'm a user on a Jupyterhub system that is not spawning things in a way that sources my bashrc, is there anything I can do to have it do so correctly?

**Comment by rcthomas** [comment]
@marius311 if you just need this for a kernel (and not the notebook), you can make the kernel-spec run a wrapper script doing `bash -l` and set all kinds of at that level.  There's an example here

https://docs.nersc.gov/services/jupyter/#customizing-kernels-with-a-helper-shell-script

(But not with the `bash -l` but you can make that change if you want).  A starter solution would be to create the kernel-spec the usual way (say via IJulia?) and then edit the kernel-spec file, migrating the kernel launch command to the separate helper bash script.

**Comment by rkdarst** [comment]
@rcthomas, do you know of [envkernel](https://github.com/NordicHPC/envkernel) which I've recently made?  I could add a "login-shell" mode to it which makes a login shell before running whatever kernel command.  Perhaps it could be useful for your cases, too...

If I manage to do this tomorrow I'll post here again.

**Comment by marius311** [comment]
Thanks for the link @rcthomas. Based on that I've got the following slightly simplified solution. First, create a file `kernel-helper.sh`:

```
#!/bin/bash -il
exec "$@"
```

and then edit my `kernel.json` and just insert `"/path/to/kernel-helper.sh"` as the first entry in `"argv"`. This is nice since it requires minimal edits to `kernel.json` and should work for any type of kernels. Note I needed both `-il` in my case, not just `-l`, but I now get a kernel running in exactly the same environment as my login shell, which is what I wanted. 

And thanks @rkdarst, that looks like it basically automates this process and with more flexibility. Will definitely check it out.
