### ISSUE TITLE
Allow location of home directories to be configured

### ISSUE THREAD

**Issue by ellisonbg** [jupyter/jupyterhub#342]
When JupyterHub is run with `create_system_users` it would be nice to be able to configure the locations of the home directories (something other than `/home`). I think this can be done with the `-d /otherhome` flag to the `useradd` command.

**Comment by minrk** [comment]
Do you want JupyterHub-created users to have different home directories than other users on the system? If not, it's probably best to specify HOME in `/etc/default/useradd` rather than changing the call JupyterHub makes. Added in #344, anyway.
