### ISSUE TITLE
Default shell to bash

### ISSUE THREAD

**Issue by ellisonbg** [jupyter/jupyterhub#348]
Right now, if users are created by jupyterhub with useradd on a stock Ubuntu, there is no default shell. This leads to `/bin/sh` being used rather than bash. When the web terminal is opened all readline related actions (tab, up, down) don't work. I know I can configure this in `/etc/default/useradd`, but we jut added an option to set the home directory base path. Should we default the shell to bash in the useradd CLI call? Maybe add an config option that defaults to `/bin/bash`. This behavior means that a pretty standard config on Ubuntu will have a (slightly) broken terminal.

I could have sworn that we did something on this previously, when I was debugging things with my Active Directory setup where `SHELL` wasn't being set. But I don't remember what we ended up doing (I may have just set it myself).

Thoughts?

**Comment by minrk** [comment]
I think the previous bug had to do with how the user's shell was looked up, not how it is set initially, so that would have been slightly different, but I'm not 100% sure.

I think the problem may be that we are using `useradd` instead of `adduser`, which has different defaults. When I create a user with `adduser`, the default shell is bash.

For reference, the non-interactive `adduser` call is:

    adduser -q --gecos "" --disabled-password new2

(and totally different on BSD, of course)

We could also add a `useradd_args`, so that all args are exposed. I would prefer not to add a configurable for every option, so a passthrough to useradd (or adduser) would be the easiest way to make sure you can set whatever you need.

**Comment by ellisonbg** [comment]
Min, thanks for the thoughtful response.


I think the problem may be that we are using useradd instead of adduser,
> which has different defaults. When I create a user with adduser, the
> default shell is bash.
>
> For reference, the non-interactive adduser call is:
>
> adduser -q --gecos "" --disabled-password new2
>
>
I had a look at the config for adduser and it does look a bit more sane
that useradd. It is also equally easy to configure using the config file.

>  (and totally different on BSD, of course)
>
> We could also add a useradd_args, so that all args are exposed. I would
> prefer not to add a configurable for every option, so a passthrough to
> useradd (or adduser) would be the easiest way to make sure you can set
> whatever you need.
>
What about using adduser so the defaults are a bit more sane and then
adding a adduser_args that is string valued to provide extra flags?

Or, another option that would address the BSD difference would be to have a
single command for user creation that is templated by the username, with a
default like:

'adduser -q --gecos "" --disabled-password {username}'

That would be the most flexible and have pretty sane default behavior. I
almost like that best as it makes it easy to get working for other setups
as well.



> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/jupyterhub/issues/348#issuecomment-163048387>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by minrk** [comment]
> What about using adduser so the defaults are a bit more sane and then adding a adduser_args that is string valued to provide extra flags?

I think that's the most sensible. Possibly with an escape hatch for producing the complete command.

**Comment by minrk** [comment]
Switched to adduser by default and allow fully custom add_user_cmd in #349. Let me know what you think.

**Comment by ellisonbg** [comment]
Great, I will have a look. Thanks!

On Thu, Dec 10, 2015 at 2:24 PM, Min RK <notifications@github.com> wrote:

> Switched to adduser by default and allow fully custom add_user_cmd in #349
> <https://github.com/jupyter/jupyterhub/pull/349>. Let me know what you
> think.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/jupyterhub/issues/348#issuecomment-163766961>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com
