### ISSUE TITLE
Set sqlalchemy in requirements.txt to version 0.8 or later

### ISSUE THREAD

**Issue by willingc** [jupyter/jupyterhub#350]
As reported by Rob Moser on the mailing list, there is an import error when a sqlalchemy version less than 0.8 is used. See https://github.com/zzzeek/sqlalchemy/blob/master/lib/sqlalchemy/inspection.py
inspect (which we use) was not added until 0.8.

We should update the ``requirements.txt`` file to either pin the sqlalchemy version or set a greater than version.

**Comment by minrk** [comment]
Updated in #352

**Comment by willingc** [comment]
Thanks @minrk
