### ISSUE TITLE
hub api/users last_activity differs from api/proxy's last_activity

### ISSUE THREAD

**Issue by IngoS11** [jupyter/jupyterhub#361]
I have implemented the [cull_idle_servers.py](../blob/master/examples/cull-idle/cull_idle_servers.py) in our landscape to remove single user notebook servers that people left without proper closing and noticed that the last_activity in the api coming back from /api/users is not correctly reflecting user behavior whereas the last_activity in routes inside /api/proxy seems to be. I have not fully figured out how this works, but I believe that last_activity is only reset when something is done in the hub like `Stop Server` or `Admin` whereas the `last_activity` in /api/proxy is also reset when users work within their notebooks or just have one open as this creates traffic going though the proxy. I believe a better example for culling servers would be to leverage the /api/proxy api instead of /api/users.

**Comment by minrk** [comment]
last_activity is updated periodically, but not constantly. It is accurate within `JupyterHub.last_activity_interval`, which defaults to five minutes.

**Comment by IngoS11** [comment]
Sorry, I did not take the time to read the commend above cull_idle_servers.py. I was just surprised to see two variables that, to me, where to do the "same thing" behave differently. What would be the better approach if you needed more frequent updates, change the last_activity_interval or read from /api/proxy?

**Comment by minrk** [comment]
`/api/proxy` didn't exist when `cull_idle_servers.py` was written. I still think talking to the Hub's users API is probably preferable, since it doesn't require the additional HTTP request made *by* the Hub to the proxy. If you need higher resolution, you can set `JupyterHub.last_activity_interval` to a smaller value:

```python
# jupyterhub_config.py
c.JupyterHub.last_activity_interval = 120 # two minutes
```

You probably don't want it to be *much* finer than that, though.

**Comment by IngoS11** [comment]
Hi minrk,
makes sense. Thanks for the clarification.
