### ISSUE TITLE
404 on single user notebook server anytime I restart jupyterhub

### ISSUE THREAD

**Issue by ellisonbg** [jupyter/jupyterhub#362]
I just deployed jupyterhub from scratch using my ansible scripts this morning. The script are unchanged from 2-3 weeks ago when I did it previously and it was all working. I am running from latest master of jupyterhub.

Anytime I restart jupyterhub (hub+proxy) I see the following behavior:

* I can log in (using GitHub OAuth)
* Trying to start my server gives me a 404 on `/hub/users/ellisonbg`. I can tell from the server log that the single user server isn't being started.
* I can go to the Admin page and start my server from there.
* But then, I get a redirect loop when I try to go to my single user server.
* If I clear all my cookies while my single user server (started through the Admin page) is still running, it starts to work as expected. I can start and stop the single user server on the control panel page just fine.
* If a restart jupyterhub, the problems start all over again.

I am using a fixed proxy_auth_token and cookie secret.

**Comment by ellisonbg** [comment]
OK tracking this down a bit:

In this line of code there is a redirect to a URL that has `users` in it:

https://github.com/jupyter/jupyterhub/blob/master/jupyterhub/handlers/pages.py#L74

But I don't see any handlers targeting URLs with `users`. I do, however, see one that targets `users` (singular) here:

https://github.com/jupyter/jupyterhub/blob/master/jupyterhub/handlers/base.py#L482

Looks like this is a bug that crept in in the recent spawner form work. I will pin my work to a hash that is before that work for now. More than willing to test fixes for this though.

**Comment by ellisonbg** [comment]
I just installed this SHA:

https://github.com/jupyter/jupyterhub/commit/2f1a2036999cd5ab02a720af62ea698645d2a8b5

and everything works fine. This doesn't explain exactly what the problem is, but it does bisect it to the recent spawner work.

HTH!

**Comment by minrk** [comment]
Thanks! I know what's going wrong, just need to figure out why...

**Comment by minrk** [comment]
one-character typo in the URL. #364 fixes it and adds tests for good measure.

**Comment by ellisonbg** [comment]
Thanks!

On Thu, Dec 31, 2015 at 3:07 AM, Min RK <notifications@github.com> wrote:

> one-character typo in the URL. #364
> <https://github.com/jupyter/jupyterhub/pull/364> fixes it and adds tests
> for good measure.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/jupyterhub/issues/362#issuecomment-168171343>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com
