### ISSUE TITLE
Bugs related to usernames

### ISSUE THREAD

**Issue by ellisonbg** [jupyter/jupyterhub#369]
Today I ran into a couple of bugs related to usernames on a JupyterHub deployment (GitHub OAuth, automatic user account creation (adduser).

* Some students had usernames with CamelCase and other chars `-`.
* When I used the Admin pages to add such a user, adduser failed (could see in the logs) because the format didn't match the allowable regexp (Ubuntu 15.04 default).
* But, after that failed attempt, adding users with valid usernames also failed, until I restarted the server.

Possible steps to take:

* Normalize usernames (lowercase, strip other chars).
* Add the `--force-badname` option to all `adduser` calls  to get the system to accept the usernames.
* Better error handling so this error doesn't mess up the servers state like that.
* Better error reporting so admins can see what is going on better.

**Comment by minrk** [comment]
I'm most curious about how one bad name could get it stuck in a bad state that would prevent creating new users. I'm looking into that one now. The other issues probably belong in the LocalGitHubAuthenticator.

**Comment by minrk** [comment]
Fixed the reused user issue in #371. What would you like as an error message in the UI? Should it contain the full traceback, just the error string, or "See server logs for more details"?

As for what to do in the LocalGitHubAuth about usernames, I think it was only the camelCase users that caused the problem. When I tested, the hyphens were not considered an issue. Did you see something different? What would you prefer do do about that? I see a few options:

1. normalize to lowercase for *all usernames always*
1. normalize to lowercase in the base LocalAuthenticator (seems like too much to me)
1. normalize to lowercase always with GitHub OAuth (GitHub usernames are not case sensitive, though they can have a reference case for display)
1. normalize only on LocalGitHubOAuth

Any other options?

**Comment by ellisonbg** [comment]
I didn't test to see if names with `-` failed as well. Mainly the camel
case.

I think the options you describe are pretty comprehensive.

I think the main factor I am thinking about is that any Authenticator which
can create users:

* Should have a clear specification of what types of usernames are allowed.
* When the Admin pane is used to add a user that doesn't match that format,
we tell the admin "Sorry, that username has invalid characters."

Furthermore, any Authenticator that can create users which accepts
usernames from another service (such as GitHub):

* Should either 1) accept all valid usernames that service supports
(--force-badname in adduser) or 2) normalize the names to be acceptable to
adduser. I think that --force-badname is probably a --bad-idea in general
though.
* Should also warn appropriately on the Admin page.

Seems like there are two related change then:

* Allow *some* Authenticators to have a regular expression that is used to
match usernames
* Have a normalization API that Authenticators can override for doing
normalizations that are appropriate.



On Wed, Jan 6, 2016 at 6:34 AM, Min RK <notifications@github.com> wrote:

> Fixed the reused user issue in #371
> <https://github.com/jupyter/jupyterhub/pull/371>. What would you like as
> an error message in the UI? Should it contain the full traceback, just the
> error string, or "See server logs for more details"?
>
> As for what to do in the LocalGitHubAuth about usernames, I think it was
> only the camelCase users that caused the problem. When I tested, the
> hyphens were not considered an issue. Did you see something different? What
> would you prefer do do about that? I see a few options:
>
>    1. normalize to lowercase for *all usernames always*
>    2. normalize to lowercase in the base LocalAuthenticator (seems like
>    too much to me)
>    3. normalize to lowercase always with GitHub OAuth (GitHub usernames
>    are not case sensitive, though they can have a reference case for display)
>    4. normalize only on LocalGitHubOAuth
>
> Any other options?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/jupyterhub/issues/369#issuecomment-169338196>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by minrk** [comment]
I think both proposals are a good idea. I wouldn't use the username regex on local usernames, though, since the underlying user creation already does this, and there's always a chance for the two to get out of sync. There is already an informative error on a bad username, we just don't propagate it to the UI.

**Comment by minrk** [comment]
Should be all set in #373
