### ISSUE TITLE
Unable to reference a Data File that's stored in a child directory

### ISSUE THREAD

**Issue by chandragaajula** [jupyter/jupyterhub#376]
I'm able to access a data file that's stored in the Home Directory, like this:

    import csv
    file = open("unisex_names_table.csv")
    csvreader = csv.reader(file)
    airline_safety = list(csvreader)
    print(airline_safety)

However, I'm unable to access the data file when it's stored in a child directory like: /data/fivethirtyeight_data/unisex-names/unisex_names_table.csv

![jupyterdatafiles_2](https://cloud.githubusercontent.com/assets/2474552/12240792/5206e506-b844-11e5-9cba-ad30c146470b.JPG)

![jupyterdatafiles_3](https://cloud.githubusercontent.com/assets/2474552/12240859/9f5b1af2-b844-11e5-85c7-c130740937b7.JPG)

I've tried multiple combinations in referencing the data file in child directories, but haven't been successful. Is there a solution to this?

**Comment by andreaslang** [comment]
You are referencing absolutely starting from the root of the file system. This is probably not where your home directory is located. You want to reference relative to your home directory which you can do easily with:

```
...
file = open("~/data/fivethirtyeight_data/unisex-names/unisex_names_table.csv")
...
```

The tilde character (~) is a short cut for your home directory which is usually located at _/home/\<your-username\>_.

**Comment by chandragaajula** [comment]
@andreaslang, I see your point. However, my setup and hence my reference to Home is different. I run Jupyter from a Docker image as follows:

docker run -d -p 8888:8888 -v /home/chandra/projects/codesamples/notebooks:/home/ds/notebooks dataquestio/python3-starter

So, the Home directory for me is "/home/chandra/projects/codesamples/notebooks".

Having said that, your note did lead me to the solution:

    import csv
    file = open("/home/ds/notebooks/data/fivethirtyeight_data/unisex-names/unisex_names_table.csv")
    csvreader = csv.reader(file)
    airline_safety = list(csvreader)
    print(airline_safety)

Ideally, I would like to avoid referencing "/home/ds/notebooks" in my path. But, I can live with it.

@andreaslang - Thanks for your input. Helped me solve my problem.

**Comment by andreaslang** [comment]
I edited in a second solution in my post which should help you avoid using /home/ds in your code. See above.

**Comment by chandragaajula** [comment]
@andreaslang - No luck with your second recommendation:

![jupyterdatafiles_4](https://cloud.githubusercontent.com/assets/2474552/12243328/bfba476a-b852-11e5-849c-d545ca537400.JPG)
