### ISSUE TITLE
c.KernelSpecManager.whitelist config variable has no effect

### ISSUE THREAD

**Issue by facha** [jupyter/jupyterhub#384]
I was trying to limit jupyterhub to use just one kernel with c.KernelSpecManager.whitelist config variable:

`c.KernelSpecManager.whitelist = {'python2'}`

However it doesn't take effect. Is anyone else observing this?

**Comment by minrk** [comment]
Where did you specify this config?

**Comment by facha** [comment]
In jupyterhub_config.py file. Then I launch jupyterhub like this:

```jupyterhub -f jupyterhub_config.py```

There are other config variables set in  jupyterhub_config.py file. They are being applied with no problem.

**Comment by minrk** [comment]
You probably want to put that in `/etc/jupyter/jupyter_notebook_config.py`. It's an option for the regular single-user notebook server, not JupyterHub itself. Putting it in `jupyterhub_config.py` will have no effect.
