### ISSUE TITLE
Set JupyterHub Proxy to listen on localhost only

### ISSUE THREAD

**Issue by mogthesprog** [jupyter/jupyterhub#385]
Hi Guys,

I've configured a reverse proxy in apache to provide ssl to a number of services running on the same node. The only thing i need to do now is stop jupyterhub responding to queries which don't come from 127.0.0.1.

Is there a config line I can write to sort this out?

Cheers

**Comment by minrk** [comment]
set

```python
c.JupyterHub.ip = '127.0.0.1'
```

in `jupyterhub_config.py`

**Comment by mogthesprog** [comment]
Cheers @minrk. I figured this out in the end.
