### ISSUE TITLE
[Docs] Markdown links are not handled properly by Sphinx if referencing local doc

### ISSUE THREAD

**Issue by willingc** [jupyter/jupyterhub#390]
See http://jupyterhub.readthedocs.org/en/latest/getting-started.html#further-reading 

Custom authenticators and spawners links redirect to a "Not Found" page. This is due to Sphinx not handling markdown links to local files correctly. I will research if there is an automatic workaround. If not, we could link to the RTD rendered pages such as: http://jupyterhub.readthedocs.org/en/latest/authenticators.html

**Comment by minrk** [comment]
I think it's just the file extension that doesn't get handled, so a relative link to `./authenticators.html` should work, rather than needing to hardcode the whole URL.
