### ISSUE TITLE
jupyterhub login 500 : Internal Server Error

### ISSUE THREAD

**Issue by sourceindex** [jupyter/jupyterhub#409]
Hi,

i installed jupyterhub as mentioned on the wiki with sudospawner an getting the following error after login:

    500 : Internal Server Error
    Spawner failed to start [status=0]

with the following settings:

    cat /etc/sudoers
    Cmnd_Alias JUPYTER_CMD = /usr/local/bin/sudospawner
    jupyterhub ALL=(%jupyterhub) NOPASSWD:JUPYTER_CMD

    cat /etc/passwd
    jupyterhub:x:1001:1002::/usr/local/share/jupyter/hub:/bin/bash

    cat /etc/group
    shadow:x:42:jupyterhub
    jupyterhub:x:1002:xxxxxx

the log shows:

    tail -f /var/log/auth.log
    Feb  2 09:02:18 xxxxxxxx python3: pam_group(login:setcred): unable to set the group membership for user: Operation not permitted
    Feb  2 09:02:18 xxxxxxxx python3: pam_limits(login:session): Could not set limit for 'nofile' to soft=65536, hard=65536: Operation not permitted; uid=1001,euid=1001
    Feb  2 09:02:18 xxxxxxxx python3: pam_lastlog(login:session): unable to open /var/log/lastlog: Permission denied
    Feb  2 09:02:18 xxxxxxxx python3: pam_unix(login:session): session opened for user xxxxxxxx by (uid=1001)
    Feb  2 09:02:18 xxxxxxxx dbus[734]: [system] Rejected send message, 2 matched rules; type="method_call", sender=":1.10" (uid=1001 pid=703 comm="/usr/bin/python3 /usr/local/bin/jupyterhub --confi") interface="org.freedesktop.login1.Manager" member="CreateSession" error name="(unset)" requested_reply="0" destination="org.freedesktop.login1" (uid=0 pid=709 comm="/lib/systemd/systemd-logind ")
    Feb  2 09:02:18 xxxxxxxx python3: pam_systemd(login:session): Failed to create session: Access denied
    Feb  2 09:02:18 xxxxxxxx sudo: jupyterhub : TTY=unknown ; PWD=/ ; USER=xxxxxxxx ; COMMAND=/usr/local/bin/sudospawner

and:

    tail -f /var/log/jupyterhub/jupyterhub.log
    [I 2016-02-02 09:03:53.235 JupyterHub log:100] 302 GET / (@192.168.0.123) 3.67ms
    [I 2016-02-02 09:03:53.238 JupyterHub log:100] 302 GET /hub (@192.168.0.123) 0.71ms
    [I 2016-02-02 09:03:53.246 JupyterHub log:100] 302 GET /hub/ (@192.168.0.123) 1.05ms
    [W 2016-02-02 09:04:17.207 JupyterHub web:1521] 500 POST /hub/login?next= (192.168.0.123): Spawner failed to start [status=0]
    [E 2016-02-02 09:04:17.216 JupyterHub log:99] {
          "X-Forwarded-For": "192.168.0.123,192.168.0.123",
          "X-Forwarded-Port": "80",
          "Content-Type": "application/x-www-form-urlencoded",
          "X-Forwarded-Server": "xxx.xxx.xx",
          "Accept-Language": "en-US,en;q=0.8",
          "Connection": "close",
          "X-Forwarded-Host": "xxx.xxx.xx",
          "Upgrade-Insecure-Requests": "1",
          "Referer": "https://xxx.xxx.xx/hub/login",
          "Accept-Encoding": "gzip, deflate",
          "Content-Length": "34",
          "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
          "X-Forwarded-Proto": "http",
          "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/47.0.2526.106 Chrome/47.0.2526.106 Safari/537.36",
          "Cache-Control": "max-age=0",
          "Host": "xxx.xxx.xx",
          "Origin": "https://xxx.xxx.xx"
        }
    [E 2016-02-02 09:04:17.219 JupyterHub log:100] 500 POST /hub/login?next= (@192.168.0.123) 10202.52ms

any hints?

**Comment by sourceindex** [comment]
This where my installation steps:

```
aptitude install npm nodejs-legacy python3-pip
npm install -g configurable-http-proxy
pip3 install jupyterhub
pip3 install notebook
pip3 install git+https://github.com/jupyter/sudospawner
```

```
useradd --home-dir '/usr/local/share/jupyter/hub' --shell '/bin/bash' jupyterhub
mkdir /etc/jupyterhub /var/log/jupyterhub
chown -R jupyterhub:jupyterhub /etc/jupyterhub /var/log/jupyterhub /usr/local/share/jupyter/hub
```

```
jupyterhub --generate-config /etc/jupyterhub/jupyterhub_config.py

vi /etc/jupyterhub/jupyterhub_config.py
c.JupyterHub.data_files_path = '/usr/local/share/jupyter/hub'
c.JupyterHub.db_url = 'sqlite:///usr/local/share/jupyter/hub/jupyterhub.sqlite'
c.JupyterHub.cookie_secret_file = '/usr/local/share/jupyter/hub/jupyterhub_cookie_secret'
c.JupyterHub.base_url = '/'
c.JupyterHub.hub_ip = '0.0.0.0'
c.JupyterHub.pid_file = '/usr/local/share/jupyter/hub/jupyterhub.pid'
c.JupyterHub.spawner_class = 'sudospawner.SudoSpawner'
```

```
cat << 'EOF' | tee -a /etc/sudoers
Cmnd_Alias JUPYTER_CMD = /usr/local/bin/sudospawner
jupyterhub ALL=(%jupyterhub) NOPASSWD:JUPYTER_CMD
EOF

```

```
useradd --create-home --password 'password' --shell /bin/bash xxxxxxxx
```


```
usermod -a -G jupyterhub xxxxxxxx
usermod -a -G shadow jupyterhub
```

```
sudo -u jupyterhub sudo -n -u xxxxxxxx sudospawner --help
sudo -u jupyterhub jupyterhub --config /etc/jupyterhub/jupyterhub_config.py
```

```
cat << 'EOF' | tee /etc/systemd/system/jupyterhub.service
[Unit]
Description=Jupyterhub
Documentation=https://github.com/jupyter/jupyterhub
After=network.target

[Service]
User=jupyterhub
ExecStart=/usr/local/bin/jupyterhub --config /etc/jupyterhub/jupyterhub_config.py
ExecReload=/bin/kill -HUP $MAINPID
KillMode=process
Restart=on-failure

[Install]
WantedBy=multi-user.target
EOF
```

```
systemctl daemon-reload
systemctl enable jupyterhub.service
```

**Comment by sourceindex** [comment]
I found in another issue running jupyterhub-singleuser for debugging:
```
su - xxxxxxxx
jupyterhub-singleuser --user=xxxxxxxx --port=38268 --cookie-name=jupyter-hub-token-xxxxxxxx --base-url=/user/xxxxxxxx --hub-prefix=/hub/ --hub-api-url=http://localhost:8081/hub/api --ip=localhost --debug
```
and got this output:
```
#xxxxxxxx@xxxxxxxx:~$ jupyterhub-singleuser --user=xxxxxxxx --port=38268 --cookie-name=jupyter-hub-token-xxxxxxxx --base-url=/user/xxxxxxxx --hub-prefi=/hub/ --hub-api-url=http://localhost:8081/hub/api --ip=localhost --debug
/usr/local/lib/python3.4/dist-packages/IPython/utils/traitlets.py:5: UserWarning: IPython.utils.traitlets has moved to a top-level traitlets package.
  warn("IPython.utils.traitlets has moved to a top-level traitlets package.")
[D 2016-02-02 23:15:00.504 xxxxxxxx application:258] Config changed:
[D 2016-02-02 23:15:00.504 xxxxxxxx application:259] {'SingleUserNotebookApp': {'ip': 'localhost', 'user': 'xxxxxxxx', 'base_url': '/user/xxxxxxxx', 'hub_api_url': 'http://localhost:8081/hub/api', 'port': 38268, 'hub_prefix': '/hub/', 'log_level': 10, 'cookie_name': 'jupyter-hub-token-xxxxxxxx'}}
[D 2016-02-02 23:15:00.506 xxxxxxxx application:178] Searching ['/home/xxxxxxxx', '/home/xxxxxxxx/.jupyter', '/usr/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files
[D 2016-02-02 23:15:00.506 xxxxxxxx application:526] Looking for jupyter_config in /etc/jupyter
[D 2016-02-02 23:15:00.506 xxxxxxxx application:526] Looking for jupyter_config in /usr/local/etc/jupyter
[D 2016-02-02 23:15:00.507 xxxxxxxx application:526] Looking for jupyter_config in /usr/etc/jupyter
[D 2016-02-02 23:15:00.507 xxxxxxxx application:526] Looking for jupyter_config in /home/xxxxxxxx/.jupyter
[D 2016-02-02 23:15:00.507 xxxxxxxx application:526] Looking for jupyter_config in /home/xxxxxxxx
[D 2016-02-02 23:15:00.508 xxxxxxxx application:526] Looking for jupyter_notebook_config in /etc/jupyter
[D 2016-02-02 23:15:00.508 xxxxxxxx application:526] Looking for jupyter_notebook_config in /usr/local/etc/jupyter
[D 2016-02-02 23:15:00.508 xxxxxxxx application:526] Looking for jupyter_notebook_config in /usr/etc/jupyter
[D 2016-02-02 23:15:00.508 xxxxxxxx application:526] Looking for jupyter_notebook_config in /home/xxxxxxxx/.jupyter
[D 2016-02-02 23:15:00.508 xxxxxxxx application:526] Looking for jupyter_notebook_config in /home/xxxxxxxx
[D 2016-02-02 23:15:00.510 xxxxxxxx application:258] Config changed:
[D 2016-02-02 23:15:00.510 xxxxxxxx application:259] {'SingleUserNotebookApp': {'ip': 'localhost', 'cookie_name': 'jupyter-hub-token-xxxxxxxx', 'user': 'xxxxxxxx', 'hub_api_url': 'http://localhost:8081/hub/api', 'port': 38268, 'base_url': '/user/xxxxxxxx', 'hub_prefix': '/hub/', 'log_level': 10}}
Traceback (most recent call last):
  File "/usr/local/bin/jupyterhub-singleuser", line 237, in <module>
    main()
  File "/usr/local/bin/jupyterhub-singleuser", line 233, in main
    return SingleUserNotebookApp.launch_instance()
  File "/usr/local/lib/python3.4/dist-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/traitlets/config/application.py", line 588, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-114>", line 2, in initialize
  File "/usr/local/lib/python3.4/dist-packages/traitlets/config/application.py", line 74, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/notebook/notebookapp.py", line 1023, in initialize
    self.init_webapp()
  File "/usr/local/bin/jupyterhub-singleuser", line 203, in init_webapp
    s['hub_api_key'] = env.pop('JPY_API_TOKEN')
  File "/usr/lib/python3.4/_collections_abc.py", line 552, in pop
    value = self[key]
  File "/usr/lib/python3.4/os.py", line 633, in __getitem__
    raise KeyError(key) from None
KeyError: 'JPY_API_TOKEN'
```

any ideas?

**Comment by sourceindex** [comment]
https://github.com/jupyter/sudospawner/pull/10

**Comment by minrk** [comment]
@sourceindex thanks for the quick fix!

**Comment by fossouo** [comment]
Face the same problem how to fix it ?

**Comment by sourceindex** [comment]
@fossouo you just pointed at it.

the error is up in the description and the fix is in the spawn command.

https://github.com/jupyter/sudospawner/pull/10/files

**Comment by brandonmp** [comment]
just wanted to add in case someone else faces this:

i was getting the 500 error as well, but it turns out it was due to the drive being full.  clearing space fixed this.

**Comment by vilhelmen** [comment]
Chiming in just to add that you will see the pam_group(login:setcred) error if you forget to add the jupyter user to the shadow group, which is a step in @sourceindex's setup.
