### ISSUE TITLE
Proxy error on user spawn but not admin spawn.

### ISSUE THREAD

**Issue by ryanlovett** [jupyter/jupyterhub#410]
In some cases, when our hub users click on My Server to start their server, the hub responds with an HTTP 503. When this happens, admins can click on "start server" for the user from the Admin page and "stop server" to stop. The user can then hit My Server without error.

When the user does see the 503, the routing table has an entry for them pointing at a spawned container that no longer exists. I don't know how relevant this is because it plays no part in the admin being able to start the server. The user's server spawned by the admin ends up with an updated entry in the routing table (new node/ip).

We're using [swarmspawner](https://github.com/data-8/jupyterhub-deploy/blob/master/roles/jupyterhub/files/swarmspawner.py).

**Comment by ryanlovett** [comment]
This went away with a restart of the hub container. We haven't seen recurring issues with the 503 since.

**Comment by minrk** [comment]
Interesting! Hopefully it's fixed. Do you have logs saved that we might dig through for insight?

**Comment by ryanlovett** [comment]
No logs from that time period unfortunately. I'll leave this open for maybe a few more weeks in case it pops up, but we haven't seen this particular issue for a while.

**Comment by minrk** [comment]
After spending some time in your logs, I found a race condition that should be fixed by #445

**Comment by minrk** [comment]
Thanks for the debugging info!

**Comment by ryanlovett** [comment]
Awesome, thanks very much!
