### ISSUE TITLE
Unexpected behavior with UserSpawnHandler

### ISSUE THREAD

**Issue by kafonek** [jupyter/jupyterhub#412]
I am trying to implement a custom Authenticator that will let our team click on links to Jupyter url's and bring up the notebook without being redirected to the login splash screen and then needing to navigate to a specific notebook.  In our setup, the Nginx front-end web server is performing authentication automatically for us and setting the user token via a proxy_set_header before reverse proxying to our Jupyter webserver.

```python
# jupyterhub_configs.py

from jupyterhub.auth import Authenticator
from jupyterhub.handlers import BaseHandler
from jupyterhub.utils import url_path_join
from traitlets import Unicode
from tornado import gen, web
import re

class NginxHandler(BaseHandler):
    def get(self):
        "designed to run behind an Nginx reverse proxy that tags user auth in a proxy_set_header"
        username = self.request.headers.get("user_auth")
        if not username:
            raise web.HTTPError(401, "Something has gone wrong with the Nginx authentication")
        user = self.user_from_username(username)
        self.set_login_cookie(user)

        next_url = self.get_argument('next', '')
        if next_url:
            pattern = re.compile('/user/[a-z0-9]+/')
            substitute = '/user/%s/' % username
            new_url = re.sub(pattern, substitute, next_url)
            self.redirect(new_url)
        else:
            # Hub runs from / so we can navigate throughout our VM,
            # but want to launch from "login" page straight to the notebook directory
            self.redirect(url_path_join(self.hub.server.base_url, 'user/%s/tree/opt/jupyter/notebooks' % username))

class NginxAuthenticator(Authenticator):
    login_service = Unicode("Secure login")
    def login_url(self, base_url):
        return url_path_join(base_url, 'nginx_login')

    def get_handlers(self, app):
        return [(r'/nginx_login', NginxHandler)]

    @gen.coroutine
    def authenticate(self, handler, data):
        raise NotImplementedError()

c.JupyterHub.authenticator_class = NginxAuthenticator
```

My single-user view after logging in looks like this: https://myserver/jupyter/kafonek/tree/opt/jupyter/notebooks

My hope is that when someone else links me to their landing page, then the UserSpawnHandler (jupyterhub/handlers/base.py, line 453) will direct me to the LoginHandler url (with a 'next' url argument), then my custom LoginHandler will rewrite the 'next' url and direct me on to the right page.  I think the steps should look like this:

1) My colleague links me https://myserver/jupyter/user/bob/notebooks/opt/jupyter/notebooks/Untitled.ipynb
2) based on the default handlers in base.py, clicking that link calls UserSpawnHandler.get('bob')
3) UserSpawnHandler see's that I'm actually kafonek, and not bob so it redirects me to the custom LoginHandler.login_url with the 'next' url argument
4) Custom login handler authenticates me and redirects me to https://myserver/jupyter/user/kafonek/notebooks/opt/jupyter/notebooks/Untitled.ipynb

That process happens.. sometimes.  Intermittently.  About half the time, it seems that UserSpawnHandler.get is not called.  Instead in the jupyter logs I just see:

"[I <timestamp> bob log:47] 302 GET /jupyter/user/bob/notebooks/opt/jupyter/notebooks/Untitled.ipynb"
"[I <timestamp> kafonek log:47] 302 GET /jupyter/user/mrkafon"

Using firebug, I see that the first redirection is sending me to https://myserver/jupyter/hub/?next=... instead of https://myserver/jupyter/hub/nginx_login?next=...

I'm completely stumped as to why that is happening.

**Comment by minrk** [comment]
First, when bob sends you that link, it is to a private URL that you may never visit. There is no indication, for instance, that `/user/you/path` points to the same file as `/user/other/path`, since the norm is for these to point to respective home directories or containers, or some similarly isolated filesystem.

Some details:

1. when kafonek visits /user/bob/path, that request is handled by Bob's single-user server, not the Hub. Authentication will fail, and kafonek will be redirected to the Hub.
2. single-user servers have `login_url` set to `/hub/`, rather than inheriting login_url from the Hub (this might be a bug, but it's what's happening now).
3. kafonek visits `/hub/`, and may or may not be logged in. This is handled by RootHandler, which does a few things depending on the state:
  - if not logged in, redirect to login_url
  - if logged in and running, redirect to kafonek's single-user server
  - if logged in and not running, redirect to /hub/home, the landing page

I'm not sure if there's a great way for a link to `/user/foo/path` to end up redirecting user bar to `/user/bar/path`, which usually doesn't make any sense.

**Comment by kafonek** [comment]
Thanks for the education minrk.

Understood about the norm being for notebooks/files to be in home directories or containers.  In our setup specifically, we intend on having notebooks/files be saved into a directory visible by all so that we can jump into each others notebooks.

I see now.  The times where the redirect was working would have been when the user didn't have a single-user server already running yet.  I.e., I change my url from /user/kafonek/test.ipynb to /user/bob/test.ipynb, and if bob doesn't have a single-user server running yet, then the UserSpawnHandler sends me back to NginxAuthenticator and everything works.

But if bob does have a single-user server running, then it directs me to the Hub.  Where could I change how the single-user server redirects when authentication fails?  BaseHandler (jupyterhub/handlers/base.py line 363) seems to inherit the login_url from self.settings['login_url'].  Should I be looking somewhere else?

Thanks again for all your help.

**Comment by kafonek** [comment]
Minrk,

I hardcoded the s['login_url'] in SingleUserNotebookApp.init_webapp in jupyterhub/singleuser.py and that seems to have done the trick.

s['login_url'] = self.hub_prefix + 'nginx_login'

**Comment by willingc** [comment]
Adding @kafonek's post from gitter. Thanks @kafonek.

![screen shot 2016-06-22 at 3 00 20 pm](https://cloud.githubusercontent.com/assets/2680980/16285430/ea0f6f46-388a-11e6-8c73-17066f85932d.png)
