### ISSUE TITLE
Make the logo image easily customizable

### ISSUE THREAD

**Issue by yuvipanda** [jupyter/jupyterhub#418]
Right now you have to modify page.html template (or replace the static/images/jupyter.png. This is a common customization, so we should make this be available as a configurable parameter.

**Comment by minrk** [comment]
Makes sense. The only hairy bit is the separation of Hub and single-user servers, which means that the only reasonable choice is for it to be a URL if we want it to affect both. Should be easy enough, though.

**Comment by minrk** [comment]
#423 adds the option
