### ISSUE TITLE
Make use of Docker links

### ISSUE THREAD

**Issue by Fokko** [jupyter/jupyterhub#420]
Hi,

First of all, very good work of Dockerizing the Jupyterhub environment. I really love it. I am trying to get a fully Dockerized setup, so the Jupyerhub and the spawners all in separate containers. I found out a potential way of simplifying the setup.

Instead of using IP's to point back to the jupyterhub, I think it is a good idea to create native Dockerlinks links between the jupyterhub and the workers, so the workers can easily connect back to the jupyterhub based on the hostname.

This requires a few steps:

- A static name of the jupyterhub to create a link.
- Link the worker to the jupyterhub container at startup.
- Point to the jupterhub hostname instead of an ip.

I will create a pull-request in the upcoming week.

**Comment by minrk** [comment]
Does that require any changes to JupyterHub? While some arguments are called 'ip', hostnames should actually be accepted.

**Comment by Fokko** [comment]
This PR on the dockerspawner:
https://github.com/jupyter/dockerspawner/pull/69

This PR on the jupyterhub itself, to add a label to reference the container:
https://github.com/jupyter/jupyterhub/pull/421

By using the config:
```
c.JupyterHub.spawner_class = 'dockerspawner.DockerSpawner'
c.DockerSpawner.use_docker_links = True
c.DockerSpawner.use_internal_ip = True
c.DockerSpawner.hub_ip_connect = 'jupyterhub'
```
The Jupyterhub will automatically link the newly spawned container to itself. The child container will connect back to the hub by using the `jupyterhub` alias which has been created.

This PR will also a step towards better Docker Swarm support.

**Comment by Fokko** [comment]
Thanks guys!
