### ISSUE TITLE
Can't share links to notebooks

### ISSUE THREAD

**Issue by akaihola** [jupyter/jupyterhub#424]
I use the Docker spawner and have the following volume configuration:

    c.DockerSpawner.volumes = {'/notebooks/Users/{username}': '/notebooks/Home'}
    c.DockerSpawner.read_only_volumes = {'/notebooks/Users': '/notebooks/Users'}

I can create a notebook at `http://myserver/user/akaihola/notebooks/Users/akaihola/example.ipynb` and view it as another user at `http://myserver/user/friend/notebooks/Users/akaihola/example.ipynb`

But, if I send the link `http://myserver/user/akaihola/notebooks/Users/akaihola/example.ipynb` to a friend, he can't just log in to the server and click on the link since `/user/akaihola/` doesn't match his username.

It would be convenient if JupyterHub would redirect from `/user/akaihola/*` to `/user/friend/*` automatically when the username in the URL doesn't match the logged in user.

**Comment by danielballan** [comment]
For sharing notebooks between users, I am trying out an `/examples` server extension, [nbexamples](https://github.com/danielballan/nbexamples). Maybe it will be of use to you.

**Comment by jpugliesi** [comment]
This documentation explains how to make a JupyterHub link "shareable" in that it will redirect a user to their own single-user server: https://jupyterhub.readthedocs.io/en/stable/reference/urls.html#user-redirect
