### ISSUE TITLE
Add @takluyver's excellent beginner tips to docs

### ISSUE THREAD

**Issue by willingc** [jupyter/jupyterhub#425]
From Google Group https://groups.google.com/forum/#!topic/jupyter/UKsfe65TFm0

@takluyver answered a beginner's questions about planning for a JupyterHub deployment. The response was helpful, clear, and all around :sparkles: 

@takluyver, Let me know if you wish to add or if you would like me to add. I would even use :gb: english ;)

cc/@fperez

**Comment by fperez** [comment]
Thanks!! LMK if I can help...

**Comment by fperez** [comment]
Many thanks!!

On Sat, Feb 13, 2016 at 11:12 AM, Carol Willing <notifications@github.com>
wrote:

> Closed #425 <https://github.com/jupyter/jupyterhub/issues/425> via #426
> <https://github.com/jupyter/jupyterhub/pull/426>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/jupyterhub/issues/425#event-549573888>.
>



-- 
Fernando Perez (@fperez_org; http://fperez.org)
fperez.net-at-gmail: mailing lists only (I ignore this when swamped!)
fernando.perez-at-berkeley: contact me here for any direct mail
