### ISSUE TITLE
[questions] Hub url without /<user>/ in url

### ISSUE THREAD

**Issue by Carreau** [jupyter/jupyterhub#454]
Hey, 

I was asked the other days at BIDS if it was possible to run the HUB with a URL scheme that never have the user name in it.
Basically having the HTTP Proxy redirect on the right server only based on Cookie or something else. 

I was not able to give a definitive answer of wether it was currently possible.

**Comment by minrk** [comment]
This is not possible. Many different aspects rely on the users' servers having different URL prefixes.

**Comment by Carreau** [comment]
Ok, thanks, that's what I thought. 
maybe we can try to keep this case in mind for the future.
