### ISSUE TITLE
change jupyterhub configuration params by command line

### ISSUE THREAD

**Issue by anaderi** [jupyter/jupyterhub#458]
Was trying to change `c.Spawner.container_ip` jupyterhub param by `--Spawner.ip` command line argument, but seems that those are not the same. Would it be possible to make `c.Spawner.container_ip` controllable by jupyterhub invocation, so I could override without config file modifications?
(juptyerhub version 0.5.1)

I guess it is not the only parameter that is not accessible by command line args. 

PS am I right that configuration file params are of higher priority than command-line ones? (say, I cannot override `c.JupyterHub.authenticator_class` by `--JupyterHub.authenticator_class` command-line one?

**Comment by minrk** [comment]
All configurable options are technically configurable on the command-line, even if some are really inconvenient to type. Just replace the `c.Class.trait` with `--Class.trait`. In this case, you probably need `--DockerSpawner.container_ip=...`, since Spawner doesn't have a container_ip trait.
