### ISSUE TITLE
ImportError: No module named 'pysqlite2'

### ISSUE THREAD

**Issue by gracehllee** [jupyter/jupyterhub#464]
I installed jupyterhub in Centos7, and get the error:# jupyterhub
[I 2016-03-07 11:02:28.695 JupyterHub app:523] Loading cookie_secret from /home/vxlan/Downloads/jupyterhub_cookie_secret
[E 2016-03-07 11:02:28.700 JupyterHub app:1117]
    Traceback (most recent call last):
      File "/usr/local/lib/python3.4/site-packages/jupyterhub/app.py", line 1114, in launch_instance_async
        yield self.initialize(argv)
      File "/usr/local/lib/python3.4/site-packages/jupyterhub/app.py", line 929, in initialize
        self.init_db()
      File "/usr/local/lib/python3.4/site-packages/jupyterhub/app.py", line 590, in init_db
        **self.db_kwargs
      File "/usr/local/lib/python3.4/site-packages/jupyterhub/orm.py", line 392, in new_session_factory
        engine = create_engine(url, **kwargs)
      File "/usr/local/lib/python3.4/site-packages/sqlalchemy/engine/__init__.py", line 386, in create_engine
        return strategy.create(*args, **kwargs)
      File "/usr/local/lib/python3.4/site-packages/sqlalchemy/engine/strategies.py", line 75, in create
        dbapi = dialect_cls.dbapi(**dbapi_args)
      File "/usr/local/lib/python3.4/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 339, in dbapi
        raise e
      File "/usr/local/lib/python3.4/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 334, in dbapi
        from pysqlite2 import dbapi2 as sqlite
    ImportError: No module named 'pysqlite2'

How should I do ?

Grace

**Comment by Carreau** [comment]
Hum, this seem to be a `sqlalchemy` error as `sqlalchemy` cannot import `pysqlite2`. 
You likely want to install `pysqlite2`.

**Comment by gracehllee** [comment]
I try to install pysqlite2 with pip3, then I got the error as following:
Python-3.4.4]# pip3 install psyqlite2
Collecting psyqlite2
  Could not find a version that satisfies the requirement psyqlite2 (from versions: )
No matching distribution found for psyqlite2

**Comment by Carreau** [comment]
Python 3 should [import `sqlite3`](https://github.com/zzzeek/sqlalchemy/blob/0e7904e730c3d2b0d3a394ad60010158ee29050c/lib/sqlalchemy/dialects/sqlite/pysqlite.py#L331-L340) 

what does a `from sqlite3 import dbapi2 as sqlite` in a python shell gives ?

You are likely to be missing sqlite binding for your python install (that come with python, not as python a package) 

Maybe a install `libsqlite3-dev` as [suggested here](http://stackoverflow.com/questions/1210664/no-module-named-sqlite3).

**Comment by gracehllee** [comment]
Thanks @Carreau , 
I install sqlite-devel again, and reinstall python3.4,
it is working now

**Comment by Carreau** [comment]
Great ! Closing !

**Comment by natbusa** [comment]
@gracehllee @Carreau 
http://stackoverflow.com/questions/1210664/no-module-named-sqlite3

**Comment by bing-he** [comment]
I use Python 3.6 on Mac. I have the same problems and I could not install libsqulite3-dev.
143:~ User$ jupyter-notebook 
......
    from pysqlite2 import dbapi2 as sqlite3
ModuleNotFoundError: No module named 'pysqlite2'

143:~ User$ pip install libsqlite3-dev
Collecting libsqlite3-dev
  Could not find a version that satisfies the requirement libsqlite3-dev (from versions: )
No matching distribution found for libsqlite3-dev

I did the same command and it worked.
conda install sqlite
conda install python=3.6

**Comment by ruhidagdelen** [comment]
on mac i did
brew install sqlite
and it worked 👍

**Comment by RomainSabathe** [comment]
I'm bumping onto this error as well. I don't have a lot of context so maybe what I'm saying is nonsense, but isn't it possible to wrap the `from pysqlite2 import dbapi2 as sqlite3` in a try/except block? And it fails, it imports from `sqlite3` directly? Scratching my head at the moment. I use pyenv to manage and install python on my system.

**Comment by kadu9** [comment]
brew install sqlite
This one worked for me on Mac with python3.6.5 version

**Comment by AndreasSchaetti** [comment]
I did the following:

Copy C:\ProgramData\Anaconda3\Library\bin\sqlite3.dll to C:\ProgramData\Anaconda3\DLLs\sqlite3.dll

I had to perform the same trick to fix a similar error involving SSL.
