### ISSUE TITLE
How to change jupyterhub configuration?

### ISSUE THREAD

**Issue by gracehllee** [jupyter/jupyterhub#465]
I use "jupyterhub --generate-config" to generate the configuration file named: jupyterhub_config.py.
 run "jupyterhub --no-ssl -f jupyterhub_config.py" it was still read jupyterhub default configuration.
How could I modify the jupyterhubb configuration?
How could I  enable multiple user mode and change port number....

**Comment by minrk** [comment]
It should read the config file. What do you see if you add `--debug`?

**Comment by gracehllee** [comment]
There are some errors in file jupyterhub_config.py, such as typo, formatting or other careless mistake that  will make jupyterhub always read the default configuration.
add --debug shows it was read jupyterhub_config.py.
