### ISSUE TITLE
Can not add additional items to environment of Spawner

### ISSUE THREAD

**Issue by yuvipanda** [jupyter/jupyterhub#476]
```
c.Spawner.env.update({
    'wat': 'waaaaaaaaaaaat'
})
```

Seems to have no effect. Is this because env is just a `Dict` without `config=True` set in the Spawner base class?

**Comment by minrk** [comment]
That's right, env is not configurable at the moment. We can rearrange a few things to make that work.

**Comment by yuvipanda** [comment]
Just adding config=True to the declaration doesn't seem to be enough, for some reason. I probably just don't understand traitlets well enough, heh.

**Comment by minrk** [comment]
#479 should make env configurable
