### ISSUE TITLE
User creation fails on CentOS

### ISSUE THREAD

**Issue by dayer4b** [jupyter/jupyterhub#484]
As indicated here, the `adduser` command is given the `-q` parameter to suppress STDOUT.

https://github.com/jupyter/jupyterhub/blob/master/jupyterhub/auth.py#L282

However, this fails on CentOS 7.  `adduser` there is literally a symlink to `useradd`.  I'd recommend changing the `adduser` command to simply use `useradd` with the appropriate options for compatibility with all major GNU/Linux distros.

**Comment by dayer4b** [comment]
I should add that the `-q` parameter isn't the only problem.  Basically, all the parametersfaile.  However, in my tests, this seems to get the job done:

```bash
useradd -m --home-dir /home/username -r username
```

**Comment by minrk** [comment]
It seems like it should load all of the defaults in `adduser.conf` that `useradd` ignores, so I don't think useradd is actually the right thing most of the time. You can specify a custom `Authenticator.add_user_cmd` to be whatever is most appropriate for your system.

**Comment by dayer4b** [comment]
oh!  a custom option. Sorry I didn't know.  I'll try that.  Thanks!

**Comment by dayer4b** [comment]
wow, that worked.  is this documented?

**Comment by willingc** [comment]
@dayerb We're glad you got that to work :sunny:

Here's what we currently have documented:
- [Writing a custom authenticator](https://jupyterhub.readthedocs.org/en/latest/authenticators.html)
- [JupyterHub API](https://jupyterhub.readthedocs.org/en/latest/api/auth.html#module-jupyterhub.auth)
Please feel free to make suggestions on the above documents.
