### ISSUE TITLE
"ImportError: cannot import name 'Unicode'" after Anaconda upgrade

### ISSUE THREAD

**Issue by alexvorobiev** [jupyter/jupyterhub#489]
I have just updated Anaconda packages for jupyterhub (`conda upgrade --all`) and now jupyterhub refuses to start:

Traceback (most recent call last):
  File "/my/path/to/anaconda/envs/jupyterhub/bin/jupyterhub", line 3, in <module>
    from jupyterhub.app import main
  File "/my/path/to/anaconda/envs/jupyterhub/lib/python3.5/site-packages/jupyterhub/app.py", line 35, in <module>
    from traitlets import (
ImportError: cannot import name 'Unicode'

**Comment by alexvorobiev** [comment]
It turned out conda didn't fully install traitlets package. I reinstalled it and now everything is back to normal.

**Comment by MohammadHeydari** [comment]
I already insall Text_Unicode by anaconda official channel commands but it doesn't work at all.

by from text_unidecode import unicode command it gives me this error: `ModuleNotFoundError: No module named 'unicode'`
