### ISSUE TITLE
AttributeError: 'module' object has no attribute 'sleep'

### ISSUE THREAD

**Issue by e9t** [jupyter/jupyterhub#492]
Hi, thanks for the great project!
I've successfully launched jupyterhub on one of my servers and enjoying it, but having some trouble setting it up in another server.

Running jupyterhub right after installation, I am getting the following error:

<pre>
$ jupyterhub --no-ssl
[I 160329 09:44:33 app:572] Writing cookie_secret to /home/e9t/jupyterhub_cookie_secret
[W 160329 09:44:34 app:292] 
    Generating CONFIGPROXY_AUTH_TOKEN. Restarting the Hub will require restarting the proxy.
    Set CONFIGPROXY_AUTH_TOKEN env or JupyterHub.proxy_auth_token config to avoid this message.
    
[W 160329 09:44:35 app:685] No admin users, admin interface will be unavailable.
[W 160329 09:44:35 app:686] Add any administrative users to `c.Authenticator.admin_users` in config.
[I 160329 09:44:35 app:712] Not using whitelist. Any authenticated user will be allowed.
[I 160329 09:44:35 app:1113] Hub API listening on http://127.0.0.1:8081/hub/
[W 160329 09:44:35 app:851] Running JupyterHub without SSL. There better be SSL termination happening somewhere else...
[I 160329 09:44:35 app:860] Starting proxy @ http://*:8000/
[C 160329 09:44:35 app:1119] Failed to start proxy
    Traceback (most recent call last):
      File "/usr/local/lib/python3.4/dist-packages/jupyterhub/app.py", line 1117, in start
        yield self.start_proxy()
      File "/usr/lib/python3/dist-packages/tornado/gen.py", line 395, in get_result
        return self.runner.pop_result(self.key).result()
      File "/usr/lib/python3/dist-packages/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/usr/lib/python3/dist-packages/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/usr/lib/python3/dist-packages/tornado/gen.py", line 476, in set_result
        self.run()
      File "/usr/local/lib/python3.4/dist-packages/jupyterhub/app.py", line 883, in start_proxy
        yield server.wait_up(1)
      File "/usr/lib/python3/dist-packages/tornado/gen.py", line 395, in get_result
        return self.runner.pop_result(self.key).result()
      File "/usr/lib/python3/dist-packages/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/usr/lib/python3/dist-packages/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/usr/lib/python3/dist-packages/tornado/gen.py", line 476, in set_result
        self.run()
      File "/usr/local/lib/python3.4/dist-packages/jupyterhub/orm.py", line 110, in wait_up
        yield wait_for_server(self.ip or '127.0.0.1', self.port, timeout=timeout)
      File "/usr/lib/python3/dist-packages/tornado/gen.py", line 395, in get_result
        return self.runner.pop_result(self.key).result()
      File "/usr/local/lib/python3.4/dist-packages/jupyterhub/utils.py", line 58, in wait_for_server
        yield gen.sleep(0.1)
    AttributeError: 'module' object has no attribute 'sleep'
    

$ 09:44:35.200 - info: [ConfigProxy] Proxying http://*:8000 to http://127.0.0.1:8081
09:44:35.203 - info: [ConfigProxy] Proxy API at http://127.0.0.1:8001/api/routes
</pre>

Then, when I go to `http://<my_ip>:8000` on my browser, I get the following error messages at my terminal:

<pre>
09:44:56.477 - error: [ConfigProxy] Proxy error:  code=ECONNREFUSED, errno=ECONNREFUSED, syscall=connect
09:44:56.477 - error: [ConfigProxy] 503 GET /
09:44:56.779 - error: [ConfigProxy] Proxy error:  code=ECONNREFUSED, errno=ECONNREFUSED, syscall=connect
09:44:56.779 - error: [ConfigProxy] 503 GET /favicon.ico
09:45:42.052 - error: [ConfigProxy] Proxy error:  code=ECONNREFUSED, errno=ECONNREFUSED, syscall=connect
09:45:42.052 - error: [ConfigProxy] 503 GET /
09:45:42.411 - error: [ConfigProxy] Proxy error:  code=ECONNREFUSED, errno=ECONNREFUSED, syscall=connect
09:45:42.411 - error: [ConfigProxy] 503 GET /favicon.ico
</pre>

and on my browser:

<pre>
  <h1>503: Proxy Target Missing</h1>
  <p>The upstream service is unavailable</p>
  <hr/>
  <p>configurable-http-proxy</p>
</pre>

The following is my environment:

<pre>
$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.3 LTS"
$ pip3 list | grep jupyter
jupyter (1.0.0)
jupyter-client (4.0.0)
jupyter-console (4.0.2)
jupyter-core (4.0.4)
jupyterhub (0.5.0)
$ configurable-http-proxy --version
1.1.0
$ sudo ufw status
Status: active

To                         Action      From
--                         ------      ----
...
8001                       ALLOW       Anywhere
8000                       ALLOW       Anywhere
...
$ npm --version
1.3.10
</pre>

I'm wondering what I'm doing wrong, because the working server I have has the same configurations with this server. Any comments would be appreciated.

**Comment by minrk** [comment]
What version of tornado? JupyterHub requires tornado ≥ 4.1, which introduces `gen.sleep`.

**Comment by e9t** [comment]
tornado was 3.1.1.
Upgraded to 4.3 and all is well. Thanks!

**Comment by rajatkmehta** [comment]
@e9t @minrk how you have upgraded to tornado ≥ 4.1 as I am getting same error while just using "pip" in command line?
AttributeError: module 'tornado.gen' has no attribute 'sleep'

**Comment by Eeyhan** [comment]
I just solve，pull down the Git source，Then install it with the command：
```python setup.py install```
