### ISSUE TITLE
 AttributeError: 'module' object has no attribute 'sleep'

### ISSUE THREAD

**Issue by sdd3** [jupyter/jupyterhub#504]
My installation of jupyterhub was working well but now something has come unstuck. 

When I start jupyterhub a first time it reports that the proxy has failed to start, then seems to go ahead and start it but exit anyway leaving the proxy running. 

```
[I 2016-04-10 09:37:02.771 JupyterHub app:558] Loading cookie_secret from /srv/jupyterhub/jupyterhub_cookie_secret
[I 2016-04-10 09:37:02.883 JupyterHub app:1113] Hub API listening on http://127.0.0.1:8081/hub/
[I 2016-04-10 09:37:02.888 JupyterHub app:860] Starting proxy @ http://80.11.11.11:8000/
[C 2016-04-10 09:37:02.903 JupyterHub app:1119] Failed to start proxy
    Traceback (most recent call last):
      File "/usr/lib/python3.4/site-packages/jupyterhub/app.py", line 1117, in start
        yield self.start_proxy()
      File "/usr/lib64/python3.4/site-packages/tornado/gen.py", line 399, in start
        self.result = self.future.result()
      File "/usr/lib/python3.4/site-packages/jupyterhub/app.py", line 883, in start_proxy
        yield server.wait_up(1)
      File "/usr/lib64/python3.4/site-packages/tornado/gen.py", line 399, in start
        self.result = self.future.result()
      File "/usr/lib/python3.4/site-packages/jupyterhub/orm.py", line 110, in wait_up
        yield wait_for_server(self.ip or '127.0.0.1', self.port, timeout=timeout)
      File "/usr/lib64/python3.4/site-packages/tornado/gen.py", line 399, in start
        self.result = self.future.result()
      File "/usr/lib/python3.4/site-packages/jupyterhub/utils.py", line 58, in wait_for_server
        yield gen.sleep(0.1)
    AttributeError: 'module' object has no attribute 'sleep'
    
[root jupyterhub]# 09:37:03.329 - info: [ConfigProxy] Proxying https://80.11.11.11:8000 to http://127.0.0.1:8081
09:37:03.333 - info: [ConfigProxy] Proxy API at http://127.0.0.1:8001/api/routes
```

The second time jupyterhub starts using the existing proxy but spawned servers fail with "500 : Internal Server Error" 

```
[I 2016-04-10 09:38:46.835 JupyterHub app:558] Loading cookie_secret from /srv/jupyterhub/jupyterhub_cookie_secret
[I 2016-04-10 09:38:46.910 JupyterHub app:1113] Hub API listening on http://127.0.0.1:8081/hub/
[I 2016-04-10 09:38:46.939 JupyterHub app:827] Proxy already running at: http://80.11.11.11:8000/
[I 2016-04-10 09:38:46.939 JupyterHub app:1136] JupyterHub is now running at http://80.11.11.11:8000/

```
```

 Traceback (most recent call last):
      File "/usr/lib64/python3.4/site-packages/tornado/web.py", line 1348, in _when_complete
        if result.result() is not None:
      File "/usr/lib/python3.4/site-packages/jupyterhub/handlers/base.py", line 484, in get
        yield self.spawn_single_user(current_user)
      File "/usr/lib64/python3.4/site-packages/tornado/gen.py", line 399, in start
        self.result = self.future.result()
      File "/usr/lib/python3.4/site-packages/jupyterhub/handlers/base.py", line 307, in spawn_single_user
        except gen.TimeoutError:
    AttributeError: 'module' object has no attribute 'TimeoutError'

```
I'm running on fedora 21 with the most recent repo versions of all packages etc, and it worked fine last night so I don't think it could be a version issue. 

Any help would be greatly appreciated.

**Comment by sdd3** [comment]
Appears two versions of pip were installed. I removed one and force reinstalled jupyterhub and notebook - seems ok again.

**Comment by minrk** [comment]
JupyterHub requires tornado 4.1, but it looks like you have older tornado. What do you get from `pip list` and `python3 -c 'import tornado; print(tornado.version)'`?

Upgrading tornado should do it:

    python3 -m pip install --upgrade tornado.

Installing jupyterhub with pip should have also forced an upgrade of tornado, but I'm not sure what could cause skipping the version check of dependencies.

**Comment by sdd3** [comment]
Thanks for reply minrk. Outputs from those commands are below. 

`
# pip list
backports.ssl-match-hostname (3.4.0.2)
chardet (2.2.1)
cssselect (0.9.1)
decorator (3.4.0)
gyp (0.1)
iniparse (0.4)
javapackages (4.1.0)
kitchen (1.2.1)
lxml (3.3.6)
pip (1.5.6)
pycurl (7.19.3.1)
pygobject (3.14.0)
pygpgme (0.3)
pyliblzma (0.5.3)
pyxattr (0.5.3)
PyXB (1.2.3)
rpm-python (4.12.0.1)
setuptools (2.0)
simplejson (3.5.3)
six (1.9.0)
slip (0.6.4)                                                                                                                                                            
slip.dbus (0.6.4)                                                                                                                                                       
tornado (3.2.2)                                                                                                                                                         
urlgrabber (3.10.1)                                                                                                                                                     
virtualenv (12.0.7)                                                                                                                                                     
wsgiref (0.1.2)
yum-metadata-parser (1.1.4)
`

`
# python3 -c 'import tornado; print(tornado.version)'
4.3
`

`
# python3 -m pip install --upgrade tornado 
Requirement already up-to-date: tornado in /usr/lib64/python3.4/site-packages
Requirement already up-to-date: backports-abc>=0.4 in /usr/lib/python3.4/site-packages (from tornado)
Cleaning up...
`

**Comment by minrk** [comment]
And it's working now that you have 4.3? What does 'temporarily resolves the problem' mean?

**Comment by sdd3** [comment]
It means that after the first forced reinstall the problem was not evident for a few hours but the same problem eventually reoccurred. Since the second forced reinstall it has not appeared again. It may be that some other installations interfered with the tornado version so I'll close this off. Thanks minrk

**Comment by minrk** [comment]
Perhaps a subsequent installation forced an old tornado to be installed later.
