### ISSUE TITLE
Add Tiago's instructions for JupyterHub on AWS Server to the wiki and/or docs

### ISSUE THREAD

**Issue by willingc** [jupyter/jupyterhub#513]
From the mailing list, this is a link to Tiago's writeup of the steps to JupyterHub on AWS Server https://sites.google.com/site/jupyterhubconfiguration/

@minrk, Will you please take a look and suggest where you think this information should be added or linked to? Thanks.

Thanks Tiago for sharing the link.

**Comment by minrk** [comment]
I think linking is probably appropriate. The only thing I don't like is that I don't believe that there should be any docs online that demonstrate how to do a public deployment of JupyterHub *without SSL*.

**Comment by willingc** [comment]
@minrk Agreed on the SSL. Perhaps we could set up a wiki page that people could submit links for their use cases (and we could state that the links are use at your own risk and we recommend always deploying a public system with SSL). Thoughts?

**Comment by minrk** [comment]
There's already [a wiki](https://github.com/jupyter/jupyterhub/wiki) associated with this repo, but I haven't figured out a good way to maintain it. I do think wiki-style is attractive for things like capacity planning, deployments, etc., but I don't know a good way to structure or manage it.

**Comment by willingc** [comment]
I think I have an idea about the wiki which would be to add a links page under the community section of the Sphinx docs to some of the wiki pages. The hard thing with the wiki pages is that they are hard for users to discover. Perhaps adding the titles and links into the Sphinx docs would help.

**Comment by minrk** [comment]
I agree that discoverability is the hardest part. Links should definitely help.

**Comment by willingc** [comment]
I'll create a mock up page later today for Sphinx and submit as a WIP PR.

**Comment by minrk** [comment]
Great, thanks!

**Comment by codles** [comment]
I made a few changes to the wiki and now have a running hub. Cheers.

**Comment by willingc** [comment]
@codles Thank you! 👍
