### ISSUE TITLE
Allow group read on cookie_secret_file

### ISSUE THREAD

**Issue by robnagler** [jupyter/jupyterhub#522]
The [test for bad permissions of the cookie_secret_file](https://github.com/jupyter/jupyterhub/blob/094ac451c7ceefd888a81dace5e07aa600ffc334/jupyterhub/app.py#L620) in app.py is not ideal for operating in an environment where you want to preven the process from overwriting the file. I'd like to separate concerns: the Hub process does not need to modify its configuration so it shouldn't be allowed to for security reasons. It only needs group read access. The owner of the file can then be a different user.

I think this particular test could be testing for world write, allowing normal use of group permissions to protect data:

```python
if perm & 0o007:
    self.log.error("Bad permissions on %s", secret_file)
```

Note that this test is not sufficient to protect against security errors, since an admin can set cookie_secret  in the main config file.

**Comment by minrk** [comment]
That check makes sense to me, if you'd like to make a PR.
